# WP1.5 - Volt/Var control

This notebook demonstrates the operation of the multiconductor power flow with volt/var control for smart inverters. The proof is based on the tests defined in the WP1.5 specification document. All results have been compared against openDSS to confirm their correctness.

Here the needed libraries and functions used for the tests are imported.

In [1]:
import multiconductor as mc
import multiconductor.test.testing_toolbox
from multiconductor.control import add_volt_var_control, check_ctr_sgen_stable_state, QVCurve
from pandapower.control import run_control
import pandas as pd
pd.set_option('display.float_format', '{:.12f}'.format) 
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)  
warnings.filterwarnings("ignore", category=DeprecationWarning)
import copy

In [9]:
grids = mc.test.testing_toolbox.load_all_test_grids("wp1_5_volt_var_control")

In [10]:
l = []
for name, net in grids.items():
    net = copy.deepcopy(net)
    mc.run_pf(net, run_control=True)
    c = multiconductor.test.testing_toolbox.compare_to_dss(net)
    l.append(c)
    
pd.DataFrame(l, index=grids.keys()).sort_index(key=lambda x: x.str.len())

,max_vm_pu_diff,max_va_degree_diff,max_i_from_ka_diff,max_i_to_ka_diff,max_p_from_mw_diff,max_p_to_mw_diff,max_q_from_mvar_diff,max_q_to_mvar_diff
twenty_bus_system_voltage_in_tolerance_limits_voltvar_control.pkl,0.000000009211,0.000000775841,0.000000011716,0.000000011716,0.000000002387,0.000000002458,0.000000001250,0.000000001152
twenty_bus_system_voltage_above_tolerance_limits_voltvar_control.pkl,0.000000031308,0.000005013474,0.000000088534,0.000000088534,0.000000017427,0.000000018105,0.000000013135,0.000000012050
twenty_bus_system_voltage_below_tolerance_limits_voltvar_control.pkl,0.000000058468,0.000004283510,0.000000042699,0.000000042697,0.000000010217,0.000000009914,0.000000020112,0.000000020540
twenty_bus_system_voltage_far_above_tolerance_limits_voltvar_control.pkl,0.000000035405,0.000005220698,0.000000088424,0.000000088424,0.000000017716,0.000000018766,0.000000013808,0.000000012131
twenty_bus_system_voltage_far_below_tolerance_limits_voltvar_control.pkl,0.000000014419,0.000007017862,0.000000119188,0.000000119188,0.000000027180,0.000000025430,0.000000012129,0.000000012961
four_bus_system_symmetric_voltage_in_tolerance_limits_voltvar_control.pkl,0.000000000000,0.000000019367,0.000000070471,0.000000070471,0.000000000369,0.000000000373,0.000000000050,0.000000000035
four_bus_system_asymmetric_voltage_in_tolerance_limits_voltvar_control.pkl,0.000000007773,0.000000046913,0.000000037362,0.000000037362,0.000000318237,0.000000321492,0.000001392039,0.000001403432
four_bus_system_symmetric_voltage_above_tolerance_limits_voltvar_control.pkl,0.000000000029,0.000000039989,0.000000358407,0.000000358407,0.000000073427,0.000000078117,0.000000043618,0.000000027204
four_bus_system_symmetric_voltage_below_tolerance_limits_voltvar_control.pkl,0.000000000030,0.000000022623,0.000000216354,0.000000216354,0.000000011146,0.000000010718,0.000000004395,0.000000002900
four_bus_system_asymmetric_voltage_above_tolerance_limits_voltvar_control.pkl,0.000000122788,0.000002035927,0.000000697918,0.000000697918,0.000005798199,0.000005679938,0.000027582476,0.000027168562
four_bus_system_asymmetric_voltage_below_tolerance_limits_voltvar_control.pkl,0.000000448878,0.000004547266,0.000006285595,0.000006285595,0.000026994180,0.000025712458,0.000080412396,0.000075926367
four_bus_system_symmetric_voltage_far_above_tolerance_limits_voltvar_control.pkl,0.000000000145,0.000000029390,0.000000415117,0.000000415117,0.000000049788,0.000000053005,0.000000012159,0.000000020213
four_bus_system_asymmetric_voltage_far_above_tolerance_limits_voltvar_control.pkl,0.000000553820,0.000008668984,0.000003337712,0.000003337712,0.000033631249,0.000033730010,0.000121497173,0.000121842833

# Controller white-box test

Prior to the specified testing, the volt-var controller was tested using a 2-bus system with only an external grid connected to the first bus and a controller-equipped 3-phased generator (asymmetric_sgen) to the second bus. Both buses were connected with a line with r:x ratio of 1:10. The sgen was configured to deliver symmetric active power of 120 MW at a rated nominal power of also 120 MW. The sgen did not infeed any reactive power prior to control application. The controller's control curve was chosen according to the specification document figure 2 as is the case for all the tests in this notebook. With this setup, the voltage (vm_pu) of the external grid was modified within a continuous range of (0.87, 1.1) and stepwidth 0.001, and power flows without and with controller were executed for each of the steps. The sgen's active and reactive power output response to the voltage was recorded. 

The following graph shows the resulting voltage at the sgen bus vs. the external grid voltage for both uncontrolled case (red) and controlled case (green). Voltage at the sgen bus is always a bit higher than at the external grid because of the sgen's active power infeed. The dotted and dashed lines represent the lower and upper threshold voltages of the piecewise linear control curve. It can be seen that the controller (green curve) moved the voltage closer towards the acceptable range as soon as it left the deadband (0.967 p.u. < V < 1.033 p.u).

<img src="volt_var_control_sweeptest_voltages.png" width="800">

The following graph shows the sgen's active power output (upper curve) and reactive power output (lower curve) in percent of the nominal rated apparent power, depending on the voltage at the sgen bus. It can be seen that the reactive power output exactly follows the control curve, whereas active power is derated in order to keep the total sgen apparent power output within the allowed limit set by the rated apparent power. 

<img src="volt_var_control_sweeptest_powers.png" width="800">

# Controller validation function 

In order to validate the controller operation, the function "check_ctr_sgen_stable_state" was designed to check if the sgen power output represents a valid operation point that lies on the control curve, and respects the nominal power limit:

In [12]:
net = copy.deepcopy(grids["four_bus_system_symmetric_voltage_below_tolerance_limits_voltvar_control.pkl"])

print(f"grid contains {len(net.controller)} controller(s):")
for o in net.controller.object:
    print("    ", o)

print()
print("--- Run without controllers ---")
mc.run_pf(net, run_control=False)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=0, verbose=True)
print("asymmetric_sgen:")
print(net.asymmetric_sgen[["p_mw", "q_mvar"]])
print(net.res_bus[["vm_pu"]].loc[3])

print()
print("--- Run with controllers and re-check ---")
mc.run_pf(net, run_control=True)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=0, verbose=True)
print()
print("asymmetric_sgen:")
print(net.asymmetric_sgen[["p_mw", "q_mvar"]])
print()
print(net.res_bus[["vm_pu"]].loc[3])

grid contains 1 controller(s):
     Volt/Var Controller(element_index=[(0, 0), (0, 1), (0, 2)], q_model=QModelQVCurve, saturate_sn_mva=[20.], damping_coef=4)

--- Run without controllers ---
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (1.0265200424839804)!
asymmetric_sgen:
                        p_mw         q_mvar
index circuit
0     0       1.000000000000 0.000000000000
      1       1.000000000000 0.000000000000
      2       1.000000000000 0.000000000000
               vm_pu
phase
0     0.000000000000
1     0.958958926334
2     0.958958926334
3     0.958958926334

--- Run with controllers and re-check ---

asymmetric_sgen:
                        p_mw         q_mvar
index circuit
0     0       1.000000000000 0.616456344205
      1       1.000000000000 0.616456344205
      2       1.000000000000 0.616456344205

               vm_pu
phase
0     0.000000000000
1     0.962170919607
2     0.962170919607
3     0.962170919607

As can be seen the Q values of the sgen were altered by the cotroller.

In order to create a volt/var controller one can use the function add_volt_var_control:

In [14]:
net = copy.deepcopy(grids["four_bus_system_symmetric_voltage_below_tolerance_limits_voltvar_control.pkl"])
# delete existing controllers
net.controller.drop(net.controller.index, inplace=True)

qv_curve = QVCurve(vm_points_pu=[0.92, 0.967, 1.033, 1.07], q_points_pu=[0.6, 0, 0, -0.6])
add_volt_var_control(net, element=0, qv_curve=qv_curve, et='asymmetric_sgen', mode='gang', damping_coef=4)

print(f"grid contains {len(net.controller)} controller(s):")
for o in net.controller.object:
    print("    ", o)

mc.run_pf(net, run_control=True)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=0, verbose=True)
net.asymmetric_sgen

grid contains 1 controller(s):
     Volt/Var Controller(element_index=[(0, 0), (0, 1), (0, 2)], q_model=QModelQVCurve, saturate_sn_mva=[20.], damping_coef=4)

               name  bus  from_phase  to_phase           p_mw         q_mvar  \
index circuit
0     0        None    3           1         0 1.000000000000 0.881776493069
      1        None    3           2         0 1.000000000000 0.881776493069
      2        None    3           3         0 1.000000000000 0.881776493069

               vm_pu  const_z_percent_p  const_i_percent_p  const_z_percent_q  \
index circuit
0     0          NaN     0.000000000000     0.000000000000     0.000000000000
      1          NaN     0.000000000000     0.000000000000     0.000000000000
      2          NaN     0.000000000000     0.000000000000     0.000000000000

               const_i_percent_q          sn_mva        scaling  in_service  \
index circuit
0     0           0.000000000000 20.000000000000 1.000000000000        True
      1           0.000000000000 20.000000000000 1.000000000000        True
      2           0.000000000000 20.000000000000 1.000000000000        True

               type current_source  slack control_mode  \
index circuit
0     0        None            NaN  False     Volt/Var
      1        None            NaN  False     Volt/Var
      2        None            NaN  False     Volt/Var

                                                   control_curve
index circuit
0     0        <multiconductor.control.volt_var_control.QVCur...
      1        <multiconductor.control.volt_var_control.QVCur...
      2        <multiconductor.control.volt_var_control.QVCur...

## Tests on 4-bus meshed toplogy, 3-phase system, load or sgen at bus 2 and controlled sgen at bus 3
These tests serve to demonstrate the correct operation of volt/var control of a single sgen in the following scenarios:
1. Moderate sgen power injections and bus3 voltage is well within the specified tolerance limits
2. High sgen power injections, bus3 voltage is above the threshold and controller should bring it down
3. High or load consumption at bus2, bus3 voltage is below the threshold and controller should increase it
4. Asymmetric sgen power injection, verification of control in asymmetric conditions.

With the following command we re-load the original grids (one of them was modified by previous code)

In [15]:
grids = mc.test.testing_toolbox.load_all_test_grids("wp1_5_volt_var_control")

## Test 1: 4 bus grid with one controlled sgen, symmetric load and sgen, voltage within tolerance limits
No control action. No reactive power infeed from controlled sgen, no active power change.

In [17]:
net = grids["four_bus_system_symmetric_voltage_in_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0114, 1.0114, 1.0114]
sn_mva_limit: [5.000000, 5.000000, 5.000000]
sn_mva: [5.000000, 5.000000, 5.000000]
p_mw: [5.000000, 5.000000, 5.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0114, 1.0114, 1.0114]
sn_mva_limit: [5.000000, 5.000000, 5.000000]
sn_mva: [5.000000, 5.000000, 5.000000]
p_mw: [5.000000, 5.000000, 5.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 3.0242475190789264e-13
Max overall va_degree difference: 1.9366764949259985e-08
Max overall i_from_ka difference: 7.047121530767697e-08
Max overall i_to_ka difference: 7.047121530767697e-08
Max overall p_from_mw difference: 3.6851766083145776e-10
Max overall p_to_mw difference: 3.729070385816158e-10
Max overall q_from_mvar difference: 5.010991621645644e-11
Max overall q_to_mvar difference: 3.475233989469473e-11

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999997950 0.999999997950    0.000003737157    0.000003756524
      2     0.999999997950 0.999999997950 -119.999996262843 -119.999996249932
      3     0.999999997950 0.999999997950  120.000003737157  120.000003743613
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.005495382218 1.005495382217    1.193306449436    1.193306468757
      2     1.005495382218 1.005495382217 -118.806693550564 -118.806693537698
      3     1.005495382218 1.005495382217  121.193306449436  121.193306455846
2     0     0.000000000000 0.000000000000  -63.434948822922    0.000000000000
      1     1.011491275646 1.011491275645    2.371982006049    2.371982025326
      2     1.011491275646 1.011491275645 -117.628017993951 -117.628017981130
      3     1.011491275646 1.011491275645  122.371982006049  122.371982012414
3     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.011352859910 1.011352859909    2.374280518461    2.374280537737
      2     1.011352859910 1.011352859909 -117.625719481539 -117.625719468719
      3     1.011352859910 1.011352859909  122.374280518461  122.374280524826

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       1.712575827931 1.712575898402 1.712575827931 1.712575898402
      1       1.712575827931 1.712575898402 1.712575827931 1.712575898402
      2       1.712575827931 1.712575898402 1.712575827931 1.712575898402
1     0       0.856301696466 0.856301731702 0.856301696466 0.856301731702
      1       0.856301696466 0.856301731702 0.856301696466 0.856301731702
      2       0.856301696466 0.856301731702 0.856301696466 0.856301731702
2     0       0.005719495316 0.005719495551 0.005719495316 0.005719495551
      1       0.005719495316 0.005719495551 0.005719495316 0.005719495551
      2       0.005719495316 0.005719495551 0.005719495316 0.005719495551
3     0       0.856283682053 0.856283717288 0.856283682053 0.856283717288
      1       0.856283682053 0.856283717288 0.856283682053 0.856283717288
      2       0.856283682053 0.856283717288 0.856283682053 0.856283717288

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       1.712575827931 1.712575898402 -9.882681388922 -9.882681388554
      1       1.712575827931 1.712575898402 -9.882681388922 -9.882681388553
      2       1.712575827931 1.712575898402 -9.882681388922 -9.882681388554
1     0       0.856301696466 0.856301731702 -4.970897995697 -4.970897995509
      1       0.856301696466 0.856301731702 -4.970897995697 -4.970897995509
      2       0.856301696466 0.856301731702 -4.970897995697 -4.970897995509
2     0       0.005719495316 0.005719495551 -0.000228101927 -0.000228101929
      1       0.005719495316 0.005719495551 -0.000228101927 -0.000228101929
      2       0.005719495316 0.005719495551 -0.000228101927 -0.000228101929
3     0       0.856283682053 0.856283717288 -4.970441717386 -4.970441717200
      1       0.856283682053 0.856283717288 -4.970441717386 -4.970441717200
      2       0.856283682053 0.856283717288 -4.970441717386 -4.970441717200

                  p_to_mw_mc    p_to_mw_dss q_from_mvar_mc  q_from_mvar_dss  \
index circuit
0     0       9.941339713082 9.941339712709 0.310615138773   0.310615138723
      1       9.941339713082 9.941339712709 0.310615138773   0.310615138723
      2       9.941339713082 9.941339712709 0.310615138773   0.310615138723
1     0       5.000228101927 5.000228101738 0.036055575308   0.036055575291
      1       5.000228101927 5.000228101738 0.036055575308   0.036055575291
      2       5.000228101927 5.000228101738 0.036055575308   0.036055575291
2     0       0.000229410432 0.000229410434 0.033400203500   0.033400203499
      1       0.000229410433 0.000229410434 0.033400203500   0.033400203499
      2       0.000229410433 0.000229410434 0.033400203500   0.033400203499
3     0       4.999770589567 4.999770589380 0.069255428905   0.069255428887
      1       4.999770589568 4.999770589380 0.069255428905   0.069255428887
      2       4.999770589568 4.999770589380 0.069255428905   0.069255428887

                 q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc      pl_mw_dss  \
index circuit
0     0       -0.105311004213 -0.105311004178 0.058658324160 0.058658324156
      1       -0.105311004213 -0.105311004178 0.058658324160 0.058658324156
      2       -0.105311004213 -0.105311004178 0.058658324160 0.058658324156
1     0        0.066599796500  0.066599796509 0.029330106231 0.029330106229
      1        0.066599796500  0.066599796509 0.029330106231 0.029330106229
      2        0.066599796500  0.066599796509 0.029330106231 0.029330106229
2     0       -0.033395623732 -0.033395623731 0.000001308505 0.000001308505
      1       -0.033395623732 -0.033395623731 0.000001308505 0.000001308505
      2       -0.033395623732 -0.033395623731 0.000001308505 0.000001308505
3     0        0.033395623732  0.033395623742 0.029328872182 0.029328872180
      1        0.033395623732  0.033395623742 0.029328872182 0.029328872180
      2        0.033395623732  0.033395623742 0.029328872182 0.029328872180

                  ql_mvar_mc    ql_mvar_dss
index circuit
0     0       0.205304134560 0.205304134545
      1       0.205304134560 0.205304134545
      2       0.205304134560 0.205304134545
1     0       0.102655371808 0.102655371800
      1       0.102655371808 0.102655371800
      2       0.102655371808 0.102655371800
2     0       0.000004579768 0.000004579768
      1       0.000004579768 0.000004579768
      2       0.000004579768 0.000004579768
3     0       0.102651052637 0.102651052629
      1       0.102651052637 0.102651052629
      2       0.102651052637 0.102651052629

## Test 2: 4 bus grid with one controlled sgen, symmetric load and sgen, voltage below tolerance limits
Controller to increase voltage towards tolerance band by reactive power infeed, possible active power deration

In [18]:
net = grids["four_bus_system_symmetric_voltage_below_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=0, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (1.0265200424839804)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [0.9590, 0.9590, 0.9590]
sn_mva_limit: [20.000000, 20.000000, 20.000000]
sn_mva: [1.000000, 1.000000, 1.000000]
p_mw: [1.000000, 1.000000, 1.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [0.9622, 0.9622, 0.9622]
sn_mva_limit: [20.000000, 20.000000, 20.000000]
sn_mva: [1.174742, 1.174742, 1.174742]
p_mw: [1.000000, 1.000000, 1.000000]
q_mvar: [0.616456, 0.616456, 0.616456]

--- Post control results ---
Max overall vm_pu difference: 2.976385804487336e-11
Max overall va_degree difference: 2.2623082074346712e-08
Max overall i_from_ka difference: 2.1635359814808908e-07
Max overall i_to_ka difference: 2.1635359814808908e-07
Max overall p_from_mw difference: 1.1145619538410756e-08
Max overall p_to_mw difference: 1.0718377296825565e-08
Max overall q_from_mvar difference: 4.395435126980374e-09
Max overall q_to_mvar difference: 2.9000970513948232e-09

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999973140 0.999999973140   -0.000011472716   -0.000011453350
      2     0.999999973140 0.999999973140 -120.000011472716 -120.000011459805
      3     0.999999973140 0.999999973140  119.999988527284  119.999988533739
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.975177041448 0.975177041462   -3.602248691195   -3.602248670552
      2     0.975177041448 0.975177041462 -123.602248691195 -123.602248677007
      3     0.975177041448 0.975177041462  116.397751308805  116.397751316537
2     0     0.000000000000 0.000000000000   68.198590513648   51.254105781421
      1     0.947165858076 0.947165858106   -8.745801865712   -8.745801843089
      2     0.947165858076 0.947165858106 -128.745801865712 -128.745801849544
      3     0.947165858076 0.947165858106  111.254198134288  111.254198144000
3     0     0.000000000000 0.000000000000 -104.036243467926    0.000000000000
      1     0.962170919607 0.962170919629   -6.029229374971   -6.029229353404
      2     0.962170919607 0.962170919629 -126.029229374971 -126.029229359860
      3     0.962170919607 0.962170919629  113.970770625029  113.970770633684

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       5.301915541758 5.301915758111 5.301915541758 5.301915758111
      1       5.301915541758 5.301915758111 5.301915541758 5.301915758111
      2       5.301915541758 5.301915758111 5.301915541758 5.301915758111
1     0       3.595804593176 3.595804739913 3.595804593176 3.595804739913
      1       3.595804593176 3.595804739913 3.595804593176 3.595804739913
      2       3.595804593176 3.595804739913 3.595804593176 3.595804739913
2     0       1.890665102556 1.890665179717 1.890665102556 1.890665179717
      1       1.890665102556 1.890665179717 1.890665102556 1.890665179717
      2       1.890665102556 1.890665179717 1.890665102556 1.890665179717
3     0       1.706648996915 1.706649066554 1.706648996915 1.706649066554
      1       1.706648996915 1.706649066554 1.706648996915 1.706649066554
      2       1.706648996915 1.706649066554 1.706648996915 1.706649066554

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       5.301915541758 5.301915758111  30.338889318567  30.338889307422
      1       5.301915541758 5.301915758111  30.338889318567  30.338889307422
      2       5.301915541758 5.301915758111  30.338889318567  30.338889307422
1     0       3.595804593176 3.595804739913  20.179839048512  20.179839041286
      1       3.595804593176 3.595804739913  20.179839048512  20.179839041286
      2       3.595804593176 3.595804739913  20.179839048512  20.179839041286
2     0       1.890665102556 1.890665179717 -10.337353420983 -10.337353417438
      1       1.890665102556 1.890665179717 -10.337353420983 -10.337353417438
      2       1.890665102556 1.890665179717 -10.337353420983 -10.337353417438
3     0       1.706648996915 1.706649066554   9.596844055506   9.596844052013
      1       1.706648996915 1.706649066554   9.596844055506   9.596844052013
      2       1.706648996915 1.706649066554   9.596844055506   9.596844052013

                    p_to_mw_mc      p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       -29.776683104018 -29.776683093299  4.069656270780
      1       -29.776683104018 -29.776683093299  4.069656270780
      2       -29.776683104018 -29.776683093300  4.069656270780
1     0       -19.662646579017 -19.662646572183  1.623672144043
      1       -19.662646579017 -19.662646572183  1.623672144043
      2       -19.662646579017 -19.662646572183  1.623672144043
2     0        10.480338013962  10.480338010310 -0.186501499190
      1        10.480338013962  10.480338010310 -0.186501499190
      2        10.480338013962  10.480338010310 -0.186501499190
3     0        -9.480338013962  -9.480338010559  0.478262375814
      1        -9.480338013962  -9.480338010559  0.478262375814
      2        -9.480338013962  -9.480338010559  0.478262375814

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0         4.069656266385 -2.101934519857 -2.101934516957 0.562206214549
      1         4.069656266384 -2.101934519857 -2.101934516957 0.562206214549
      2         4.069656266384 -2.101934519857 -2.101934516957 0.562206214549
1     0         1.623672142040  0.186501499189  0.186501499822 0.517192469495
      1         1.623672142040  0.186501499190  0.186501499822 0.517192469495
      2         1.623672142040  0.186501499190  0.186501499822 0.517192469495
2     0        -0.186501498804  0.686947574616  0.686947573855 0.142984592979
      1        -0.186501498804  0.686947574616  0.686947573855 0.142984592979
      2        -0.186501498804  0.686947574616  0.686947573855 0.142984592979
3     0         0.478262374918 -0.070491230410 -0.070491229826 0.116506041544
      1         0.478262374918 -0.070491230410 -0.070491229826 0.116506041544
      2         0.478262374918 -0.070491230410 -0.070491229826 0.116506041544

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       0.562206214122 1.967721750923 1.967721749427
      1       0.562206214122 1.967721750923 1.967721749427
      2       0.562206214122 1.967721750923 1.967721749428
1     0       0.517192469103 1.810173643232 1.810173641862
      1       0.517192469103 1.810173643232 1.810173641862
      2       0.517192469103 1.810173643232 1.810173641862
2     0       0.142984592872 0.500446075426 0.500446075051
      1       0.142984592872 0.500446075426 0.500446075051
      2       0.142984592872 0.500446075426 0.500446075051
3     0       0.116506041455 0.407771145404 0.407771145092
      1       0.116506041455 0.407771145404 0.407771145092
      2       0.116506041455 0.407771145404 0.407771145092

## Test 3: 4 bus grid with one controlled sgen, symmetric load and sgen, voltage above tolerance limits
Controller to decrease voltage towards tolerance band by reactive power infeed, possible active power deration

In [19]:
net = grids["four_bus_system_symmetric_voltage_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.9106225117790157)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0375, 1.0375, 1.0375]
sn_mva_limit: [25.000000, 25.000000, 25.000000]
sn_mva: [25.000000, 25.000000, 25.000000]
p_mw: [25.000000, 25.000000, 25.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0353, 1.0353, 1.0353]
sn_mva_limit: [25.000000, 25.000000, 25.000000]
sn_mva: [24.998449, 24.998449, 24.998449]
p_mw: [24.994286, 24.994286, 24.994286]
q_mvar: [-0.456210, -0.456210, -0.456210]

--- Post control results ---
Max overall vm_pu difference: 2.8543167829298e-11
Max overall va_degree difference: 3.9989085820479886e-08
Max overall i_from_ka difference: 3.584065364492517e-07
Max overall i_to_ka difference: 3.584065364492517e-07
Max overall p_from_mw difference: 7.342745789173932e-08
Max overall p_to_mw difference: 7.81171536345937e-08
Max overall q_from_mvar difference: 4.361782046657936e-08
Max overall q_to_mvar difference: 2.7203864050306947e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999933045 0.999999933045    0.000017847873    0.000017867240
      2     0.999999933045 0.999999933045 -119.999982152127 -119.999982139216
      3     0.999999933045 0.999999933045  120.000017847873  120.000017854328
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.012495013348 1.012495013319    5.964011607503    5.964011637301
      2     1.012495013348 1.012495013319 -114.035988392497 -114.035988369155
      3     1.012495013348 1.012495013319  125.964011607503  125.964011624389
2     0     0.000000000000 0.000000000000  -48.814074834290    0.000000000000
      1     1.036005604729 1.036005604710   11.715654673336   11.715654713325
      2     1.036005604729 1.036005604710 -108.284345326664 -108.284345293131
      3     1.036005604729 1.036005604710  131.715654673336  131.715654700414
3     0     0.000000000000 0.000000000000  -63.434948822922    0.000000000000
      1     1.035250706585 1.035250706565   11.728595863058   11.728595903023
      2     1.035250706585 1.035250706565 -108.271404136942 -108.271404103432
      3     1.035250706585 1.035250706565  131.728595863059  131.728595890112

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       8.361566624983 8.361566983390 8.361566624983 8.361566983390
      1       8.361566624983 8.361566983390 8.361566624983 8.361566983390
      2       8.361566624983 8.361566983390 8.361566624983 8.361566983390
1     0       4.180353490592 4.180353669790 4.180353490592 4.180353669790
      1       4.180353490592 4.180353669790 4.180353490592 4.180353669790
      2       4.180353490592 4.180353669790 4.180353490592 4.180353669790
2     0       0.031337749971 0.031337751309 0.031337749971 0.031337751309
      1       0.031337749971 0.031337751309 0.031337749971 0.031337751309
      2       0.031337749971 0.031337751309 0.031337749971 0.031337751309
3     0       4.181271808075 4.181271987286 4.181271808075 4.181271987286
      1       4.181271808075 4.181271987286 4.181271808075 4.181271987286
      2       4.181271808075 4.181271987286 4.181271808075 4.181271987286

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       8.361566624983 8.361566983390 -47.197594619770 -47.197594693197
      1       8.361566624983 8.361566983390 -47.197594619770 -47.197594693197
      2       8.361566624983 8.361566983390 -47.197594619770 -47.197594693197
1     0       4.180353490592 4.180353669790 -24.305121579082 -24.305121618263
      1       4.180353490592 4.180353669790 -24.305121579082 -24.305121618263
      2       4.180353490592 4.180353669790 -24.305121579082 -24.305121618263
2     0       0.031337749971 0.031337751309  -0.004135848914  -0.004135848723
      1       0.031337749971 0.031337751309  -0.004135848914  -0.004135848723
      2       0.031337749971 0.031337751309  -0.004135848914  -0.004135848723
3     0       4.181271808075 4.181271987286 -24.290789084353 -24.290789123288
      1       4.181271808075 4.181271987286 -24.290789084353 -24.290789123288
      2       4.181271808075 4.181271987286 -24.290789084353 -24.290789123288

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       48.595910663434 48.595910741551 10.144628601867
      1       48.595910663434 48.595910741551 10.144628601867
      2       48.595910663434 48.595910741551 10.144628601867
1     0       25.004135848914 25.004135890444  2.533947345616
      1       25.004135848914 25.004135890444  2.533947345616
      2       25.004135848914 25.004135890444  2.533947345616
2     0        0.004175131100  0.004175130909  0.187397401204
      1        0.004175131100  0.004175130909  0.187397401204
      2        0.004175131100  0.004175130909  0.187397401204
3     0       24.990110499278 24.990110540555  2.716575103425
      1       24.990110499278 24.990110540555  2.716575103425
      2       24.990110499278 24.990110540555  2.716575103425

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0        10.144628645485 -5.250522449042 -5.250522476245 1.398316043665
      1        10.144628645485 -5.250522449041 -5.250522476245 1.398316043665
      2        10.144628645485 -5.250522449042 -5.250522476245 1.398316043665
1     0         2.533947359094 -0.087397401204 -0.087397406460 0.699014269832
      1         2.533947359094 -0.087397401204 -0.087397406460 0.699014269832
      2         2.533947359094 -0.087397401204 -0.087397406460 0.699014269832
2     0         0.187397401484 -0.187259913552 -0.187259913832 0.000039282186
      1         0.187397401484 -0.187259913552 -0.187259913832 0.000039282186
      2         0.187397401484 -0.187259913552 -0.187259913832 0.000039282186
3     0         2.716575117152 -0.268950151186 -0.268950156719 0.699321414925
      1         2.716575117152 -0.268950151186 -0.268950156719 0.699321414925
      2         2.716575117152 -0.268950151186 -0.268950156719 0.699321414925

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       1.398316048354 4.894106152826 4.894106169240
      1       1.398316048354 4.894106152826 4.894106169240
      2       1.398316048354 4.894106152826 4.894106169240
1     0       0.699014272181 2.446549944413 2.446549952633
      1       0.699014272181 2.446549944413 2.446549952633
      2       0.699014272181 2.446549944413 2.446549952633
2     0       0.000039282186 0.000137487652 0.000137487652
      1       0.000039282186 0.000137487652 0.000137487652
      2       0.000039282186 0.000137487652 0.000137487652
3     0       0.699321417266 2.447624952239 2.447624960432
      1       0.699321417266 2.447624952239 2.447624960432
      2       0.699321417266 2.447624952239 2.447624960432

## Test 4: 4 bus grid with one controlled sgen, symmetric load and sgen, voltage far above tolerance limits
Controller to decrease voltage towards tolerance band by high reactive power infeed, possible active power deration

In [20]:
net = grids["four_bus_system_symmetric_voltage_far_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-5.852574003465191)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0571, 1.0571, 1.0571]
sn_mva_limit: [30.000000, 30.000000, 30.000000]
sn_mva: [30.000000, 30.000000, 30.000000]
p_mw: [30.000000, 30.000000, 30.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0440, 1.0440, 1.0440]
sn_mva_limit: [30.000000, 30.000000, 30.000000]
sn_mva: [29.938962, 29.938962, 29.938962]
p_mw: [29.819501, 29.819501, 29.819501]
q_mvar: [-2.671857, -2.671857, -2.671857]

--- Post control results ---
Max overall vm_pu difference: 1.449822484289598e-10
Max overall va_degree difference: 2.9389616074126934e-08
Max overall i_from_ka difference: 4.1511685822115396e-07
Max overall i_to_ka difference: 4.1511685822115396e-07
Max overall p_from_mw difference: 4.9787651335009286e-08
Max overall p_to_mw difference: 5.3005358324753615e-08
Max overall q_from_mvar difference: 1.2159366846731245e-08
Max overall q_to_mvar difference: 2.0212837625877e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999924895 0.999999924895    0.000021139847    0.000021159214
      2     0.999999924895 0.999999924895 -119.999978860153 -119.999978847242
      3     0.999999924895 0.999999924895  120.000021139847  120.000021146303
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.017258075080 1.017258075140    7.014293289712    7.014293314288
      2     1.017258075080 1.017258075140 -112.985706710288 -112.985706692167
      3     1.017258075080 1.017258075140  127.014293289712  127.014293301377
2     0     0.000000000000 0.000000000000  -36.869897645844    0.000000000000
      1     1.054281154583 1.054281154728   13.614040934612   13.614040962496
      2     1.054281154583 1.054281154728 -106.385959065388 -106.385959043959
      3     1.054281154583 1.054281154728  133.614040934612  133.614040949585
3     0     0.000000000000 0.000000000000  -26.565051177078    0.000000000000
      1     1.043984639092 1.043984639230   13.783881941395   13.783881970784
      2     1.043984639092 1.043984639230 -106.216118058605 -106.216118035671
      3     1.043984639092 1.043984639230  133.783881941395  133.783881957873

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       9.881257586342 9.881258001459 9.881257586342 9.881258001459
      1       9.881257586342 9.881258001459 9.881257586342 9.881258001459
      2       9.881257586342 9.881258001459 9.881257586342 9.881258001459
1     0       4.950179659073 4.950179866654 4.950179659073 4.950179866654
      1       4.950179659073 4.950179866654 4.950179659073 4.950179866654
      2       4.950179659073 4.950179866654 4.950179659073 4.950179866654
2     0       0.426499644424 0.426499662570 0.426499644424 0.426499662570
      1       0.426499644424 0.426499662570 0.426499644424 0.426499662570
      2       0.426499644424 0.426499662570 0.426499644424 0.426499662570
3     0       4.940273075455 4.940273283388 4.940273075455 4.940273283388
      1       4.940273075455 4.940273283388 4.940273075455 4.940273283388
      2       4.940273075455 4.940273283388 4.940273075455 4.940273283388

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       9.881257586342 9.881258001459 -55.903016722771 -55.903016772559
      1       9.881257586342 9.881258001459 -55.903016722771 -55.903016772559
      2       9.881257586342 9.881258001459 -55.903016722771 -55.903016772559
1     0       4.950179659073 4.950179866654 -29.054986006216 -29.054986030113
      1       4.950179659073 4.950179866654 -29.054986006216 -29.054986030113
      2       4.950179659073 4.950179866654 -29.054986006216 -29.054986030113
2     0       0.426499644424 0.426499662570  -0.035157233240  -0.035157239246
      1       0.426499644424 0.426499662570  -0.035157233240  -0.035157239246
      2       0.426499644424 0.426499662570  -0.035157233240  -0.035157239246
3     0       4.940273075455 4.940273283388 -28.800815907165 -28.800815936273
      1       4.940273075455 4.940273283388 -28.800815907165 -28.800815936273
      2       4.940273075455 4.940273283388 -28.800815907165 -28.800815936273

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       57.855801913381 57.855801966387 11.379552573074
      1       57.855801913381 57.855801966387 11.379552573074
      2       57.855801913381 57.855801966387 11.379552573074
1     0       30.035157233240 30.035157258602  1.026419920411
      1       30.035157233240 30.035157258602  1.026419920411
      2       30.035157233240 30.035157258602  1.026419920411
2     0        0.042433311707  0.042433317733  2.595820625827
      1        0.042433311707  0.042433317733  2.595820625827
      2        0.042433311707  0.042433317733  2.595820625827
3     0       29.777067909985 29.777067940856  3.518384485527
      1       29.777067909985 29.777067940856  3.518384485527
      2       29.777067909985 29.777067940856  3.518384485527

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0        11.379552564123 -4.544804405938 -4.544804385725 1.952785190610
      1        11.379552564123 -4.544804405938 -4.544804385726 1.952785190610
      2        11.379552564123 -4.544804405938 -4.544804385725 1.952785190610
1     0         1.026419908252  2.404179374173  2.404179391460 0.980171227024
      1         1.026419908252  2.404179374173  2.404179391460 0.980171227024
      2         1.026419908252  2.404179374173  2.404179391460 0.980171227024
2     0         2.595820629635 -2.570354351192 -2.570354354930 0.007276078467
      1         2.595820629635 -2.570354351192 -2.570354354930 0.007276078467
      2         2.595820629635 -2.570354351192 -2.570354354930 0.007276078467
3     0         3.518384477474 -0.101502475658 -0.101502461436 0.976252002820
      1         3.518384477474 -0.101502475658 -0.101502461436 0.976252002820
      2         3.518384477474 -0.101502475658 -0.101502461435 0.976252002820

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       1.952785193828 6.834748167136 6.834748178398
      1       1.952785193828 6.834748167136 6.834748178398
      2       1.952785193828 6.834748167136 6.834748178398
1     0       0.980171228489 3.430599294584 3.430599299711
      1       0.980171228489 3.430599294584 3.430599299711
      2       0.980171228489 3.430599294584 3.430599299711
2     0       0.007276078487 0.025466274635 0.025466274704
      1       0.007276078487 0.025466274635 0.025466274704
      2       0.007276078487 0.025466274635 0.025466274704
3     0       0.976252004582 3.416882009869 3.416882016038
      1       0.976252004582 3.416882009869 3.416882016038
      2       0.976252004582 3.416882009869 3.416882016038

## Test 5: 4 bus grid with one controlled sgen, asymmetric load and sgen, voltage within tolerance limits
No control action. No reactive power infeed from controlled sgen, no active power change.

In [21]:
net = grids["four_bus_system_asymmetric_voltage_in_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0050, 1.0114, 1.0072]
sn_mva_limit: [5.000000, 5.000000, 5.000000]
sn_mva: [2.000000, 5.000000, 3.000000]
p_mw: [2.000000, 5.000000, 3.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0050, 1.0114, 1.0072]
sn_mva_limit: [5.000000, 5.000000, 5.000000]
sn_mva: [2.000000, 5.000000, 3.000000]
p_mw: [2.000000, 5.000000, 3.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 7.77305370088918e-09
Max overall va_degree difference: 4.6912902007534285e-08
Max overall i_from_ka difference: 3.736187093039689e-08
Max overall i_to_ka difference: 3.736187093039689e-08
Max overall p_from_mw difference: 3.182370793552991e-07
Max overall p_to_mw difference: 3.2149225681621374e-07
Max overall q_from_mvar difference: 1.3920392468724785e-06
Max overall q_to_mvar difference: 1.403432365029711e-06

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.000000000221 1.000000000221    0.000001505416    0.000001524782
      2     0.999999997950 0.999999997950 -119.999996262843 -119.999996249932
      3     0.999999999676 0.999999999676  120.000002252806  120.000002259262
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.002493474010 1.002493473939    0.476665271771    0.476665289278
      2     1.005495385327 1.005495382217 -118.806693563815 -118.806693537698
      3     1.003549730617 1.003549730555  120.715968542471  120.715968546108
2     0     0.000000007773 0.000000000000   44.222789450779    0.000000000000
      1     1.005125628351 1.005125628208    0.949784852483    0.949784868240
      2     1.011491281854 1.011491275645 -117.628018028043 -117.628017981130
      3     1.007324538488 1.007324538362  121.425630501313  121.425630502253
3     0     0.000000007768 0.000000000000   44.214406016940    0.000000000000
      1     1.004986341909 1.004986341767    0.952077510696    0.952077526388
      2     1.011352866120 1.011352859909 -117.625719514640 -117.625719468719
      3     1.007185554673 1.007185554547  121.427924880326  121.427924881241

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.689550043244 0.689550067538 0.689550043244 0.689550067538
      1       1.712575875385 1.712575898402 1.712575875385 1.712575898402
      2       1.031888017028 1.031888054390 1.031888017028 1.031888054390
1     0       0.344850809650 0.344850821799 0.344850809650 0.344850821799
      1       0.856301720248 0.856301731702 0.856301720248 0.856301731702
      2       0.515987875551 0.515987894229 0.515987875551 0.515987894229
2     0       0.005748680163 0.005748680365 0.005748680163 0.005748680365
      1       0.005719495440 0.005719495551 0.005719495440 0.005719495551
      2       0.005738457204 0.005738457415 0.005738457204 0.005738457415
3     0       0.344723184330 0.344723196475 0.344723184330 0.344723196475
      1       0.856283705725 0.856283717288 0.856283705725 0.856283717288
      2       0.515916094993 0.515916113678 0.515916094993 0.515916113678

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       0.689550043244 0.689550067538 -3.980978868818 -3.980978845332
      1       1.712575875385 1.712575898402 -9.882681706791 -9.882681388553
      2       1.031888017028 1.031888054390 -5.957406335742 -5.957406305904
1     0       0.344850809650 0.344850821799 -1.995335524490 -1.995335512798
      1       0.856301720248 0.856301731702 -4.970898154232 -4.970897995509
      2       0.515987875551 0.515987894229 -2.989488266160 -2.989488251167
2     0       0.005748680163 0.005748680365 -0.000092396590 -0.000092396371
      1       0.005719495440 0.005719495551 -0.000228106006 -0.000228101929
      2       0.005738457204 0.005738457415 -0.000137991529 -0.000137991462
3     0       0.344723184330 0.344723196475 -1.995152930354 -1.995152918447
      1       0.856283705725 0.856283717288 -4.970441879970 -4.970441717200
      2       0.515916094993 0.515916113678 -2.989213928930 -2.989213913873

                  p_to_mw_mc    p_to_mw_dss  q_from_mvar_mc  q_from_mvar_dss  \
index circuit
0     0       3.990488454844 3.990488431245 -0.033425985663  -0.033425958672
      1       9.941340034201 9.941339712709  0.310613746684   0.310615138723
      2       5.978702195090 5.978702165040  0.049077908371   0.049077929228
1     0       2.000092408118 2.000092396370 -0.049990907975  -0.049990894179
      1       5.000228262092 5.000228101738  0.036054873134   0.036055575291
      2       3.000138006546 3.000137991446 -0.029352536569  -0.029352525695
2     0       0.000093718483 0.000093718264  0.033360013524   0.033360013319
      1       0.000229414512 0.000229410434  0.033400204404   0.033400203499
      2       0.000139308725 0.000139308658  0.033373383477   0.033373383327
3     0       1.999906293699 1.999906281734 -0.016718628780  -0.016718615188
      1       4.999770753773 4.999770589380  0.069254727612   0.069255428887
      2       2.999860706490 2.999860691327  0.003894937222   0.003894947947

                 q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc      pl_mw_dss  \
index circuit
0     0        0.066709536755  0.066709509367 0.009509586026 0.009509585913
      1       -0.105309600746 -0.105311004178 0.058658327411 0.058658324156
      2        0.025457599347  0.025457577747 0.021295859348 0.021295859136
1     0        0.066640000675  0.066639986681 0.004756883629 0.004756883572
      1        0.066600504376  0.066599796509 0.029330107860 0.029330106229
      2        0.066626627919  0.066626616673 0.010649740386 0.010649740280
2     0       -0.033355386898 -0.033355386694 0.000001321893 0.000001321893
      1       -0.033395624636 -0.033395623731 0.000001308505 0.000001308505
      2       -0.033368773292 -0.033368773142 0.000001317196 0.000001317196
3     0        0.033355400484  0.033355386694 0.004753363344 0.004753363288
      1        0.033396330700  0.033395623742 0.029328873804 0.029328872180
      2        0.033368784238  0.033368773142 0.010646777560 0.010646777454

                  ql_mvar_mc    ql_mvar_dss
index circuit
0     0       0.033283551091 0.033283550695
      1       0.205304145938 0.205304134545
      2       0.074535507718 0.074535506975
1     0       0.016649092700 0.016649092501
      1       0.102655377510 0.102655371800
      2       0.037274091351 0.037274090979
2     0       0.000004626626 0.000004626626
      1       0.000004579768 0.000004579768
      2       0.000004610185 0.000004610185
3     0       0.016636771704 0.016636771506
      1       0.102651058312 0.102651052629
      2       0.037263721460 0.037263721089

## Test 6: 4 bus grid with one controlled sgen, asymmetric load and sgen, voltage below tolerance limits at one phase only
Controller to increase voltage towards tolerance band by reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [22]:
net = grids["four_bus_system_asymmetric_voltage_below_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=0, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (2.5342866555417034)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0014, 0.9590, 1.0014]
sn_mva_limit: [20.000000, 20.000000, 20.000000]
sn_mva: [5.000000, 1.000000, 5.000000]
p_mw: [5.000000, 1.000000, 5.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0089, 0.9670, 1.0089]
sn_mva_limit: [20.000000, 20.000000, 20.000000]
sn_mva: [5.235011, 1.845356, 5.235011]
p_mw: [5.000000, 1.000000, 5.000000]
q_mvar: [1.550915, 1.550915, 1.550915]

--- Post control results ---
Max overall vm_pu difference: 4.488778174716046e-07
Max overall va_degree difference: 4.547266087229218e-06
Max overall i_from_ka difference: 6.285595407717892e-06
Max overall i_to_ka difference: 6.285595407717892e-06
Max overall p_from_mw difference: 2.6994180487349695e-05
Max overall p_to_mw difference: 2.5712457976112546e-05
Max overall q_from_mvar difference: 8.041239567502245e-05
Max overall q_to_mvar difference: 7.592636688547039e-05

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.000000009054 1.000000009054   -0.000000008548    0.000000010819
      2     0.999999979531 0.999999979531 -120.000011469058 -120.000011456157
      3     1.000000009054 1.000000009054  119.999999991452  119.999999997908
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.002867608879 1.002867638791   -0.049736156532   -0.049736629363
      2     0.977247624065 0.977247439907 -123.627544200055 -123.627545367513
      3     1.002867607590 1.002867637307  119.950263846560  119.950263368850
2     0     0.000000079840 0.000000079841 -130.094059612006 -130.094259273644
      1     1.002621375555 1.002621425526   -0.478582963115   -0.478583721506
      2     0.950703456179 0.950703007301 -128.760184382702 -128.760188929969
      3     1.002621372408 1.002621422053  119.521417047301  119.521416289093
3     0     0.000000012329 0.000000000000 -117.332428013263    0.000000000000
      1     1.008894369362 1.008894439022    0.277846677434    0.277845511273
      2     0.966996709745 0.966996429165 -126.086553846204 -126.086557235219
      3     1.008894367352 1.008894436559  120.277846678692  120.277845518554

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.237635312833 0.237637790955 0.237635312833 0.237637790955
      1       5.280566988791 5.280573274386 5.280566988791 5.280573274386
      2       0.237635213772 0.237637673862 0.237635213772 0.237637673862
1     0       0.297765133128 0.297765329221 0.297765133128 0.297765329221
      1       3.580886371241 3.580890676356 3.580886371241 3.580890676356
      2       0.297765129806 0.297765322481 0.297765129806 0.297765322481
2     0       0.582308444853 0.582308574014 0.582308444853 0.582308574014
      1       1.887953590161 1.887956038268 1.887953590161 1.887956038268
      2       0.582308457143 0.582308587625 0.582308457143 0.582308587625
3     0       0.330322204703 0.330323033172 0.330322204703 0.330323033172
      1       1.703417458262 1.703419507426 1.703417458262 1.703419507426
      2       0.330322182897 0.330323009125 0.330322182897 0.330323009125

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       0.237635312833 0.237637790955   0.022603574818   0.022603617564
      1       5.280566988791 5.280573274386  30.329216321666  30.329243315846
      2       0.237635213772 0.237637673862   0.022603712594   0.022603717885
1     0       0.297765133128 0.297765329221   1.673937707178   1.673937680015
      1       3.580886371241 3.580890676356  20.161827693503  20.161843739079
      2       0.297765129806 0.297765322481   1.673937788682   1.673937749314
2     0       0.582308444853 0.582308574014  -3.329608608358  -3.329608639890
      1       1.887953590161 1.887956038268 -10.351063365865 -10.351069852750
      2       0.582308457143 0.582308587625  -3.329608628367  -3.329608672027
3     0       0.330322204703 0.330323033172  -1.652463543291  -1.652463496845
      1       1.703417458262 1.703419507426   9.609700827763   9.609710494644
      2       0.330322182897 0.330323009125  -1.652463486077  -1.652463464710

                    p_to_mw_mc      p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0        -0.021474163887  -0.021474183170 -1.371801977104
      1       -29.771528521265 -29.771554233723  3.101333035544
      2        -0.021474302605  -0.021474284605 -1.371801402826
1     0        -1.670391143906  -1.670391112364 -0.412766895558
      1       -19.648917763103 -19.648932617638  1.302706973622
      2        -1.670391225489  -1.670391181824 -0.412766475449
2     0         3.343171934473   3.343171970905 -0.525179555222
      1        10.493638127954  10.493644972847 -0.492390984620
      2         3.343171955054   3.343172003676 -0.525179817065
3     0         1.656828054008   1.656828029095 -0.962988019805
      1        -9.493635576717  -9.493644973913 -0.153281239480
      2         1.656827996217   1.656827996324 -0.962987862340

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0        -1.371816229273  1.375754915363  1.375769249651 0.001129410931
      1         3.101413447940 -1.149425734142 -1.149501660509 0.557687800401
      2        -1.371815551489  1.375754337789  1.375768567972 0.001129409990
1     0        -0.412771666266  0.425179867012  0.425184653046 0.003546563272
      1         1.302763401111  0.492477782777  0.492425523932 0.512909930400
      2        -0.412771211590  0.425179446626  0.425184197808 0.003546563193
2     0        -0.525184341251  0.572651196625  0.572655999803 0.013563326115
      1        -0.492425460667  0.991402651930  0.991438381007 0.142574762089
      2        -0.525184568260  0.572651460472  0.572656229031 0.013563326688
3     0        -0.962997583385  0.978263807312  0.978273446259 0.004364510716
      1        -0.153261740602  0.559509618138  0.559491063161 0.116065251045
      2        -0.962997356381  0.978263647830  0.978273217031 0.004364510140

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       0.001129434394 0.003952938259 0.003953020378
      1       0.557689082123 1.951907301402 1.951911787431
      2       0.001129433281 0.003952934963 0.003953016483
1     0       0.003546567651 0.012412971453 0.012412986780
      1       0.512911121441 1.795184756399 1.795188925042
      2       0.003546567491 0.012412971177 0.012412986218
2     0       0.013563331015 0.047471641403 0.047471658552
      1       0.142575120097 0.499011667310 0.499012920341
      2       0.013563331649 0.047471643407 0.047471660771
3     0       0.004364532250 0.015275787507 0.015275862874
      1       0.116065520731 0.406228378658 0.406229322559
      2       0.004364531614 0.015275785490 0.015275860650

## Test 7: 4 bus grid with one controlled sgen, asymmetric load and sgen, voltage above tolerance limits at one phase only
Controller to decrease voltage towards tolerance band by reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [23]:
net = grids["four_bus_system_asymmetric_voltage_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-7.256197897351095)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0110, 1.0110, 1.0375]
sn_mva_limit: [25.000000, 25.000000, 25.000000]
sn_mva: [5.000000, 5.000000, 25.000000]
p_mw: [5.000000, 5.000000, 25.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [0.9935, 0.9935, 1.0196]
sn_mva_limit: [25.000000, 25.000000, 25.000000]
sn_mva: [6.131180, 6.131180, 24.895381]
p_mw: [5.000000, 5.000000, 24.641198]
q_mvar: [-3.548432, -3.548432, -3.548432]

--- Post control results ---
Max overall vm_pu difference: 1.2278751126970633e-07
Max overall va_degree difference: 2.03592682623821e-06
Max overall i_from_ka difference: 6.979181108590637e-07
Max overall i_to_ka difference: 6.979181108590637e-07
Max overall p_from_mw difference: 5.798199097739598e-06
Max overall p_to_mw difference: 5.679937920888278e-06
Max overall q_from_mvar difference: 2.758247573275696e-05
Max overall q_to_mvar difference: 2.7168561627988197e-05

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999973374 0.999999973374    0.000003729040    0.000003748407
      2     0.999999973374 0.999999973374 -119.999996270960 -119.999996258049
      3     0.999999911495 0.999999911495  120.000017695658  120.000017702112
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.997713057261 0.997713073366    1.328357898771    1.328357611775
      2     0.997713059584 0.997713073366 -118.671642123517 -118.671642394680
      3     1.005552328475 1.005552267880  126.069160097010  126.069160721163
2     0     0.000000058404 0.000000000000  -45.916390340778    0.000000000000
      1     0.998465869602 0.998465896483    2.620110859086    2.620110301031
      2     0.998465874112 0.998465896483 -117.379889204491 -117.379889705425
      3     1.024761654026 1.024761531239  131.974787952035  131.974789987962
3     0     0.000000055912 0.000000000000  -45.589009924756    0.000000000000
      1     0.993464090217 0.993464127239    2.704290546077    2.704289828502
      2     0.993464094959 0.993464127239 -117.295709492020 -117.295710177954
      3     1.019623318307 1.019623204494  132.037487170789  132.037488969697

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       1.845411877482 1.845411421235 1.845411877482 1.845411421235
      1       1.845411830842 1.845411421235 1.845411830842 1.845411421235
      2       8.431376053850 8.431376751768 8.431376053850 8.431376751768
1     0       0.892753193571 0.892753076713 0.892753193571 0.892753076713
      1       0.892753171022 0.892753076713 0.892753171022 0.892753076713
      2       4.216394203105 4.216394538203 4.216394203105 4.216394538203
2     0       0.206646563223 0.206646155405 0.206646563223 0.206646155405
      1       0.206646559389 0.206646155405 0.206646559389 0.206646155405
      2       0.208520297652 0.208519921738 0.208520297652 0.208519921738
3     0       0.962868441268 0.962868068639 0.962868441268 0.962868068639
      1       0.962868417070 0.962868068639 0.962868417070 0.962868068639
      2       4.217559882444 4.217560235754 4.217559882444 4.217560235754

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       1.845411877482 1.845411421235  -9.861216252328  -9.861216109442
      1       1.845411830842 1.845411421235  -9.861216398441  -9.861216109442
      2       8.431376053850 8.431376751768 -46.795071374356 -46.795065576157
1     0       0.892753193571 0.892753076713  -4.974762594001  -4.974762452664
      1       0.892753171022 0.892753076713  -4.974762608143  -4.974762452664
      2       4.216394203105 4.216394538203 -24.209369863081 -24.209367110951
2     0       0.206646563223 0.206646155405  -0.006642733557  -0.006642774903
      1       0.206646559389 0.206646155405  -0.006642846766  -0.006642774903
      2       0.208520297652 0.208519921738   0.079513181022   0.079513572300
3     0       0.962868441268 0.962868068639  -4.954564563888  -4.954564523051
      1       0.962868417070 0.962868068639  -4.954564692417  -4.954564523051
      2       4.217559882444 4.217560235754 -24.007463671620 -24.007460743811

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0        9.929327157889  9.929326975715  4.034176981220
      1        9.929327300560  9.929326975715  4.034175912882
      2       48.216833534700 48.216827854762 13.409864883646
1     0        5.006642927213  5.006642774903  1.302807070588
      1        5.006642939744  5.006642774903  1.302806551132
      2       24.920489124697 24.920486427023  3.620038294163
2     0        0.008350845781  0.008350880245  1.191225685185
      1        0.008350958927  0.008350880245  1.191225667830
      2       -0.077773952298 -0.077774349989  1.231137908325
3     0        4.991649192350  4.991649119755  2.492981741167
      1        4.991649319016  4.991649119755  2.492981204334
      2       24.718976184709 24.718973317500  4.813659028280

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0         4.034169214603 -3.795788811755 -3.795781182650 0.068110905562
      1         4.034169214603 -3.795787755466 -3.795781182650 0.068110902119
      2        13.409892466122 -8.433697322443 -8.433724491004 1.421762160344
1     0         1.302804444836 -1.191225904348 -1.191223316999 0.031880333211
      1         1.302804444836 -1.191225390529 -1.191223316999 0.031880331601
      2         3.620053062277 -1.131120878506 -1.131135456026 0.711119261616
2     0         1.191223316999 -1.185247292400 -1.185244948303 0.001708112224
      1         1.191223316999 -1.185247275266 -1.185244948303 0.001708112161
      2         1.231135455290 -1.225050607789 -1.225048177203 0.001739228725
3     0         2.492976737813 -2.363185541549 -2.363180649349 0.037084628462
      1         2.492976737813 -2.363185011239 -2.363180649349 0.037084626598
      2         4.813671428728 -2.323365232466 -2.323377420818 0.711512513090

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       0.068110866272 0.238388169465 0.238388031954
      1       0.068110866272 0.238388157416 0.238388031954
      2       1.421762278605 4.976167561203 4.976167975118
1     0       0.031880322239 0.111581166240 0.111581127837
      1       0.031880322239 0.111581160603 0.111581127837
      2       0.711119316072 2.488917415658 2.488917606251
2     0       0.001708105342 0.005978392785 0.005978368696
      1       0.001708105342 0.005978392563 0.005978368696
      2       0.001739222310 0.006087300536 0.006087278087
3     0       0.037084596704 0.129796199618 0.129796088465
      1       0.037084596704 0.129796193094 0.129796088465
      2       0.711512573689 2.490293795814 2.490294007910

## Test 8: 4 bus grid with one controlled sgen, asymmetric load and sgen, voltage far above tolerance limits
Controller to decrease voltage towards tolerance band by high reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [24]:
net = grids["four_bus_system_asymmetric_voltage_far_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=1, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [1], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-9.0)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 3
vm_pu: [1.0571, 1.0114, 1.0114]
sn_mva_limit: [30.000000, 30.000000, 30.000000]
sn_mva: [30.000000, 5.000000, 5.000000]
p_mw: [30.000000, 5.000000, 5.000000]
q_mvar: [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 3
vm_pu: [1.0281, 0.9823, 0.9823]
sn_mva_limit: [30.000000, 30.000000, 30.000000]
sn_mva: [29.820249, 7.664629, 7.664629]
p_mw: [29.248944, 5.000000, 5.000000]
q_mvar: [-5.809177, -5.809177, -5.809177]

--- Post control results ---
Max overall vm_pu difference: 5.538196927723504e-07
Max overall va_degree difference: 8.668983566550992e-06
Max overall i_from_ka difference: 3.3377119392774546e-06
Max overall i_to_ka difference: 3.3377119392774546e-06
Max overall p_from_mw difference: 3.363124929478545e-05
Max overall p_to_mw difference: 3.373000951967242e-05
Max overall q_from_mvar difference: 0.00012149717273146621
Max overall q_to_mvar difference: 0.00012184283347593805

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999999903442 0.999999903441    0.000020911868    0.000020931222
      2     0.999999958371 0.999999958371 -119.999996283120 -119.999996270208
      3     0.999999958371 0.999999958371  120.000003716881  120.000003723336
1     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.010208962570 1.010208689640    7.102591331768    7.102593409828
      2     0.992952179129 0.992952257295 -118.590442292813 -118.590443624154
      3     0.992952182371 0.992952257295  121.409557715335  121.409556369390
2     0     0.000000072362 0.000000000000 -175.025723710633    0.000000000000
      1     1.042949414758 1.042948860938   13.856697956868   13.856706625851
      2     0.990726489860 0.990726619555 -117.232787719789 -117.232790212396
      3     0.990726496134 0.990726619555  122.767212266039  122.767209781149
3     0     0.000000066985 0.000000000000 -163.795510354957    0.000000000000
      1     1.028054491955 1.028053979133   14.065749230006   14.065755770214
      2     0.982302513710 0.982302694240 -117.089831720078 -117.089835072320
      3     0.982302520416 0.982302694240  122.910168308252  122.910164921224

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       9.907787921910 9.907788080780 9.907787921910 9.907788080780
      1       2.022828978806 2.022825641094 2.022828978806 2.022825641094
      2       2.022828921609 2.022825641094 2.022828921609 2.022825641094
1     0       4.967788838257 4.967788789464 4.967788838257 4.967788789464
      1       0.936068949380 0.936068099027 0.936068949380 0.936068099027
      2       0.936068927248 0.936068099027 0.936068927248 0.936068099027
2     0       0.609325452704 0.609323508023 0.609325452704 0.609323508023
      1       0.347999161905 0.347997081076 0.347999161905 0.347997081076
      2       0.347999153737 0.347997081076 0.347999153737 0.347997081076
3     0       4.958713902306 4.958713990423 4.958713902306 4.958713990423
      1       1.109164175899 1.109161523556 1.109164175899 1.109161523556
      2       1.109164141140 1.109161523556 1.109164141140 1.109161523556

                     i_ka_mc       i_ka_dss     p_from_mw_mc    p_from_mw_dss  \
index circuit
0     0       9.907787921910 9.907788080780 -55.300137327990 -55.300103696741
      1       2.022828978806 2.022825641094  -9.829060444138  -9.829060938854
      2       2.022828921609 2.022825641094  -9.829060948667  -9.829060938854
1     0       4.967788838257 4.967788789464 -28.896531371946 -28.896517076033
      1       0.936068949380 0.936068099027  -4.974365956437  -4.974365877342
      2       0.936068927248 0.936068099027  -4.974366110590  -4.974365877342
2     0       0.609325452704 0.609323508023   0.116319520953   0.116325959290
      1       0.347999161905 0.347997081076  -0.009414761626  -0.009414816810
      2       0.347999153737 0.347997081076  -0.009414951123  -0.009414816810
3     0       4.958713902306 4.958713990423 -28.366891347877 -28.366871913781
      1       1.109164175899 1.109161523556  -4.936531235993  -4.936531532998
      2       1.109164141140 1.109161523556  -4.936531581740  -4.936531532998

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       57.263422719823 57.263388989814 14.629986306375
      1        9.910897192429  9.910897410339  6.307466996712
      2        9.910897692330  9.910897410339  6.307465599055
1     0       29.883688490922 29.883674094302  2.122159499601
      1        5.009414962443  5.009414816782  2.013191644913
      2        5.009415114940  5.009414816782  2.013190972526
2     0       -0.101468419437 -0.101474953793  3.667191545020
      1        0.014258898692  0.014258895547  1.990519818800
      2        0.014259087962  0.014258895547  1.990519783786
3     0       29.350445171493 29.350425691333  5.636327935357
      1        4.985741046810  4.985741104411  4.007846732780
      2        4.985741389473  4.985741104411  4.007846023708

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0        14.630107803547 -7.758487434958 -7.758609277792 1.963285391833
      1         6.307429654511 -6.021038377694 -6.021002004313 0.081836748291
      2         6.307429654511 -6.021036996234 -6.021002004313 0.081836743663
1     0         2.122227102903  1.332890416815  1.332822461039 0.987157118976
      1         2.013179382782 -1.890520123889 -1.890508094740 0.035049006007
      2         2.013179382782 -1.890519457303 -1.890508094740 0.035049004350
2     0         3.667177524593 -3.615212689714 -3.615199005353 0.014851101516
      1         1.990508094740 -1.973565339067 -1.973553819159 0.004844137066
      2         1.990508094740 -1.973565304850 -1.973553819159 0.004844136839
3     0         5.636382174888 -2.193889552703 -2.193943953454 0.983553823615
      1         4.007822621531 -3.835612394919 -3.835589121584 0.049209810817
      2         4.007822621531 -3.835611696642 -3.835589121584 0.049209807733

                   pl_mw_dss     ql_mvar_mc    ql_mvar_dss
index circuit
0     0       1.963285293073 6.871498871417 6.871498525756
      1       0.081836471485 0.286428619019 0.286427650199
      2       0.081836471485 0.286428602821 0.286427650199
1     0       0.987157018269 3.455049916415 3.455049563942
      1       0.035048939441 0.122671521024 0.122671288042
      2       0.035048939441 0.122671515223 0.122671288042
2     0       0.014851005497 0.051978855305 0.051978519240
      1       0.004844078737 0.016954479733 0.016954275581
      2       0.004844078737 0.016954478937 0.016954275581
3     0       0.983553777553 3.442438382654 3.442438221434
      1       0.049209571413 0.172234337861 0.172233499947
      2       0.049209571413 0.172234327066 0.172233499947

## Test 9: 20 bus grid with four controlled sgen, asymmetric load and sgen, voltage within tolerance limits
This is to test possible interactions between controlled sgens located at different points of the grid. All controllers are expected to converge at valid operation points. 
Expecting no control action. No reactive power infeed from any controlled sgen, no active power change.

In [25]:
net = grids["twenty_bus_system_voltage_in_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
for i in [0,1,2,3]:
    check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=i, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

--- Pre/Post control comparison ---
Before control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9814, 0.9897, 1.0188] / [1.0255, 1.0320, 1.0243] / [1.0199, 1.0298, 1.0097] / [1.0105, 1.0126, 1.0097]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.032000, 0.035000, 0.031500] / [0.032000, 0.035000, 0.031500] / [0.032000, 0.025000, 0.011500] / [0.032000, 0.035000, 0.031500]
p_mw: [0.032000, 0.035000, 0.031500] / [0.032000, 0.035000, 0.031500] / [0.032000, 0.025000, 0.011500] / [0.032000, 0.035000, 0.031500]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9814, 0.9897, 1.0188] / [1.0255, 1.0320, 1.0243] / [1.0199, 1.0298, 1.0097] / [1.0105, 1.0126, 1.0097]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.032000, 0.035000, 0.031500] / [0.032000, 0.035000, 0.031500] / [0.032000, 0.025000, 0.011500] / [0.032000, 0.035000, 0.031500]
p_mw: [0.032000, 0.035000, 0.031500] / [0.032000, 0.035000, 0.031500] / [0.032000, 0.025000, 0.011500] / [0.032000, 0.035000, 0.031500]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 9.211476409605415e-09
Max overall va_degree difference: 7.75841385802778e-07
Max overall i_from_ka difference: 1.1716421749463635e-08
Max overall i_to_ka difference: 1.1716410813766842e-08
Max overall p_from_mw difference: 2.3870234122647105e-09
Max overall p_to_mw difference: 2.4579882330899583e-09
Max overall q_from_mvar difference: 1.2502974836015035e-09
Max overall q_to_mvar difference: 1.1515944413342805e-09

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.000000588234 1.000000588234    0.000028658635    0.000028678004
      2     1.000001001156 1.000001001156 -119.999963741994 -119.999963729080
      3     1.000000527880 1.000000527880  120.000023958540  120.000023964997
1     0     0.000000005042 0.000000005042   98.841411059117   98.841411065795
...                    ...            ...               ...               ...
18    3     1.015139912365 1.015139914288  122.800214061376  122.800214194254
19    0     0.000000005203 0.000000005203  108.009251911593  108.009251875566
      1     0.984472629441 0.984472628965   -1.063823547752   -1.063823560556
      2     0.982768720553 0.982768720026 -120.944486341574 -120.944486357289
      3     0.984330430362 0.984330429884  119.001168750936  119.001168727062

[80 rows x 4 columns]

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.093788772227 0.093788772758 0.093789102995 0.093789103526
      1       0.076091673749 0.076091675108 0.076092041260 0.076092042619
      2       0.029270669425 0.029270668754 0.029271396048 0.029271395377
1     0       0.093789102995 0.093789103526 0.093789383402 0.093789383933
      1       0.076092041260 0.076092042619 0.076092371578 0.076092372937
      2       0.038816669485 0.038816668844 0.038816949627 0.038816948985
2     0       0.093789383402 0.093789383933 0.093789612513 0.093789613044
      1       0.092591671285 0.092591672851 0.092591802711 0.092591804276
      2       0.038816949627 0.038816948985 0.038817200513 0.038817199871
3     0       0.000002211466 0.000002211457 0.000000000115 0.000000000000
      1       0.013324870963 0.013324870959 0.013325578651 0.013325578646
      2       0.011578038989 0.011578039130 0.011578863856 0.011578863997
4     0       0.105179694452 0.105179693501 0.105179858998 0.105179858047
      1       0.119963788865 0.119963792489 0.119963983362 0.119963986986
      2       0.095174380028 0.095174379665 0.095174705369 0.095174705006
5     0       0.000002197868 0.000002197868 0.000000000000 0.000000000000
      1       0.031282352539 0.031282352741 0.031282962071 0.031282962273
      2       0.015672038203 0.015672038299 0.015672644407 0.015672644502
6     0       0.046895554373 0.046895558918 0.046896895998 0.046896900544
      1       0.073485491046 0.073485496983 0.073486176499 0.073486182437
      2       0.078408022510 0.078408027040 0.078409110845 0.078409115375
7     0       0.063315318038 0.063315322678 0.063316100997 0.063316105637
      1       0.084912470639 0.084912476731 0.084912910595 0.084912916688
      2       0.086199581168 0.086199585855 0.086200423458 0.086200428145
8     0       0.093080716057 0.093080721263 0.093081053949 0.093081059155
      1       0.101284049870 0.101284056379 0.101284277042 0.101284283552
      2       0.108448734824 0.108448740140 0.108449184905 0.108449190221
9     0       0.135116553934 0.135116560618 0.135116587456 0.135116594140
      1       0.130745243222 0.130745250851 0.130745217260 0.130745224889
      2       0.122555417330 0.122555423218 0.122555678745 0.122555684632
10    0       0.000002234033 0.000002234033 0.000000000000 0.000000000000
      1       0.010056971593 0.010056972100 0.010056358009 0.010056358516
      2       0.010054801899 0.010054802406 0.010056358009 0.010056358516
11    0       0.046896668833 0.046896670422 0.046898658840 0.046898660428
      1       0.078910378052 0.078910388364 0.078912185873 0.078912196184
      2       0.014858626384 0.014858627095 0.014859885215 0.014859885926
12    0       0.026254736789 0.026254735966 0.026256869857 0.026256869035
      1       0.078912185873 0.078912196184 0.078913951577 0.078913961889
      2       0.040106222150 0.040106222726 0.040107112770 0.040107113346
13    0       0.047871055431 0.047871056596 0.047871084094 0.047871085260
      1       0.044505572103 0.044505573010 0.044506781011 0.044506781917
      2       0.022546378333 0.022546378616 0.022546734073 0.022546734356
14    0       0.019080621670 0.019080622150 0.019080079717 0.019080080196
      1       0.024875832458 0.024875832901 0.024876825690 0.024876826134
      2       0.009261243768 0.009261244041 0.009262777173 0.009262777447
15    0       0.063051704319 0.063051700233 0.063052597517 0.063052593431
      1       0.099635046834 0.099635058395 0.099635744456 0.099635756017
      2       0.063614889024 0.063614889627 0.063615115978 0.063615116581
16    0       0.077097920339 0.077097916486 0.077098417050 0.077098413197
      1       0.109671111979 0.109671123695 0.109671589074 0.109671600790
      2       0.080135655933 0.080135656709 0.080135750656 0.080135751432
17    0       0.039115122559 0.039115123395 0.039115775880 0.039115776716
      1       0.024595534998 0.024595535669 0.024596568037 0.024596568708
      2       0.030837249941 0.030837250231 0.030837153492 0.030837153782
18    0       0.081900014853 0.081900015453 0.081900477706 0.081900478306
      1       0.081044731392 0.081044731987 0.081045513988 0.081045514583
      2       0.082344776056 0.082344776659 0.082345353914 0.082345354517

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       0.093789102995 0.093789103526 -0.021367655633 -0.021367655537
      1       0.076092041260 0.076092042619 -0.017294602871 -0.017294603122
      2       0.029271396048 0.029271395377 -0.006358298609 -0.006358298398
1     0       0.093789383402 0.093789383933 -0.021572489415 -0.021572489326
      1       0.076092371578 0.076092372937 -0.017502049285 -0.017502049546
      2       0.038816949627 0.038816948985 -0.008892478465 -0.008892478254
2     0       0.093789612513 0.093789613044 -0.021788188975 -0.021788188893
      1       0.092591802711 0.092591804276 -0.021709139361 -0.021709139633
      2       0.038817200513 0.038817199871 -0.008940066993 -0.008940066781
3     0       0.000002211466 0.000002211457  0.000000000745  0.000000000772
      1       0.013325578651 0.013325578646  0.003003610817  0.003003610803
      2       0.011578863856 0.011578863997  0.002505057115  0.002505057125
4     0       0.105179858998 0.105179858047 -0.024191881706 -0.024191881282
      1       0.119963983362 0.119963986986 -0.027554300859 -0.027554301486
      2       0.095174705369 0.095174705006 -0.021688994449 -0.021688994305
5     0       0.000002197868 0.000002197868  0.000000000285  0.000000000285
      1       0.031282962071 0.031282962273  0.007021447201  0.007021447202
      2       0.015672644407 0.015672644502  0.003511611613  0.003511611614
6     0       0.046896895998 0.046896900544 -0.008468787454 -0.008468788191
      1       0.073486176499 0.073486182437 -0.016050953437 -0.016050954598
      2       0.078409110845 0.078409115375 -0.015591194849 -0.015591195680
7     0       0.063316100997 0.063316105637 -0.013555541635 -0.013555542438
      1       0.084912910595 0.084912916688 -0.019175819932 -0.019175821149
      2       0.086200423458 0.086200428145 -0.018281455708 -0.018281456590
8     0       0.093081053949 0.093081059155 -0.021191786761 -0.021191787735
      1       0.101284277042 0.101284283552 -0.023357420358 -0.023357421693
      2       0.108449184905 0.108449190221 -0.024516410695 -0.024516411736
9     0       0.135116587456 0.135116594140 -0.031466354267 -0.031466355593
      1       0.130745243222 0.130745250851 -0.030640894661 -0.030640896275
      2       0.122555678745 0.122555684632 -0.028376535777 -0.028376536979
10    0       0.000002234033 0.000002234033 -0.000000001291 -0.000000001291
      1       0.010056971593 0.010056972100  0.002306294300  0.002306294406
      2       0.010056358009 0.010056358516  0.001699774343  0.001699774423
11    0       0.046898658840 0.046898660428  0.004219426334  0.004219427565
      1       0.078912185873 0.078912196184 -0.009880519122 -0.009880521347
      2       0.014859885215 0.014859885926 -0.002794424496 -0.002794424452
12    0       0.026256869857 0.026256869035 -0.000229552552 -0.000229551323
      1       0.078913951577 0.078913961889 -0.010054714019 -0.010054716282
      2       0.040107112770 0.040107113346 -0.008428403464 -0.008428403405
13    0       0.047871084094 0.047871085260  0.010807189451  0.010807189611
      1       0.044506781011 0.044506781917  0.008226365133  0.008226365114
      2       0.022546734073 0.022546734356  0.005141929172  0.005141929203
14    0       0.019080621670 0.019080622150  0.004139489712  0.004139489796
      1       0.024876825690 0.024876826134  0.004882597002  0.004882597004
      2       0.009262777173 0.009262777447  0.001509973444  0.001509973499
15    0       0.063052597517 0.063052593431 -0.012858473476 -0.012858472443
      1       0.099635744456 0.099635756017 -0.021167839127 -0.021167841426
      2       0.063615115978 0.063615116581 -0.014615333990 -0.014615334009
16    0       0.077098417050 0.077098413197 -0.016870504502 -0.016870503489
      1       0.109671589074 0.109671600790 -0.024170985326 -0.024170987713
      2       0.080135750656 0.080135751432 -0.018636383741 -0.018636383805
17    0       0.039115775880 0.039115776716  0.008425121786  0.008425121900
      1       0.024596568037 0.024596568708  0.004918203490  0.004918203530
      2       0.030837249941 0.030837250231  0.007249252079  0.007249252113
18    0       0.081900477706 0.081900478306  0.018436369160  0.018436369167
      1       0.081045513988 0.081045514583  0.017385304123  0.017385304128
      2       0.082345353914 0.082345354517  0.018279305226  0.018279305233

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0        0.021572489415  0.021572489326  0.003544242305
      1        0.017502049285  0.017502049546  0.003113564539
      2        0.006392478452  0.006392478240  0.002294907200
1     0        0.021788188975  0.021788188893  0.003031599962
      1        0.017709139332  0.017709139602  0.002802699069
      2        0.008940066993  0.008940066781  0.001227010876
2     0        0.021999999115  0.021999999040  0.002524528633
      1        0.021996388912  0.021996389197  0.001481942234
      2        0.008994943088  0.008994942875  0.001115616562
3     0        0.000000000027  0.000000000000 -0.000000520876
      1       -0.003000000023 -0.003000000009  0.001009857233
      2       -0.002499999995 -0.002500000005  0.001006435463
4     0        0.024500000066  0.024499999642  0.002183543385
      1        0.027978552139  0.027978552798  0.002880732355
      2        0.021988388488  0.021988388347  0.003562308590
5     0        0.000000000000 -0.000000000000 -0.000000512917
      1       -0.007000000073 -0.007000000073  0.002052993198
      2       -0.003500000000 -0.003500000000  0.001012101270
6     0        0.008555541661  0.008555542415  0.006750560943
      1        0.016175819971  0.016175821156  0.005511237194
      2        0.015781455739  0.015781456595  0.009208616626
7     0        0.013691786869  0.013691787693  0.005406952706
      1        0.019357420473  0.019357421720  0.004181139026
      2        0.018516410813  0.018516411725  0.007880067261
8     0        0.021466354498  0.021466355507  0.003646562332
      1        0.023640894902  0.023640896279  0.002749646478
      2        0.024876535927  0.024876537009  0.005467860397
9     0        0.031999999906  0.032000001292  0.001110104588
      1        0.031147728683  0.031147730365  0.000131239001
      2        0.028846199552  0.028846200807  0.003787921004
10    0       -0.000000000000 -0.000000000000 -0.000000529090
      1       -0.002303259960 -0.002303260065 -0.000652566647
      2       -0.001696739855 -0.001696739935  0.001663641181
11    0       -0.004146578453 -0.004146579670  0.009974590228
      1        0.010054714019  0.010054716282  0.015312562125
      2        0.002804534438  0.002804534397  0.001991500060
12    0        0.000251630660  0.000251629435  0.005970407257
      1        0.010228917129  0.010228919430  0.014953336057
      2        0.008485615135  0.008485615084  0.003842098744
13    0       -0.010738440379 -0.010738440535  0.000211299475
      1       -0.008166940636 -0.008166940614  0.005775059840
      2       -0.005126679115 -0.005126679145  0.000861714369
14    0       -0.004128568041 -0.004128568124 -0.001088719526
      1       -0.004864031559 -0.004864031560  0.002644356173
      2       -0.001507400259 -0.001507400313  0.001507044501
15    0        0.012966385725  0.012966384677  0.006111698305
      1        0.021462732765  0.021462735126  0.007631429271
      2        0.014748755169  0.014748755202  0.001669128803
16    0        0.017033049744  0.017033048711  0.004262385701
      1        0.024530685681  0.024530688139  0.005853665515
      2        0.018843685544  0.018843685628  0.001025221658
17    0       -0.008379221524 -0.008379221635  0.002757245781
      1       -0.004900053506 -0.004900053544  0.002723023953
      2       -0.007220724787 -0.007220724819 -0.000296604243
18    0       -0.018224169291 -0.018224169291  0.004223748063
      1       -0.017195705257 -0.017195705256  0.006932423293
      2       -0.018080125467 -0.018080125467  0.005244301814

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss  \
index circuit
0     0         0.003544242728 -0.003031599962 -0.003031600368
      1         0.003113564239 -0.002802699069 -0.002802698751
      2         0.002294907192 -0.002227010875 -0.002227010869
1     0         0.003031600368 -0.002524528633 -0.002524529024
      1         0.002802698751 -0.002481942234 -0.002481941898
      2         0.001227010869 -0.001115616562 -0.001115616558
2     0         0.002524529024 -0.001999478752 -0.001999479126
      1         0.001481941898 -0.001009857586 -0.001009857224
      2         0.001115616558 -0.001006435479 -0.001006435477
3     0        -0.000000520874  0.000000000002  0.000000000000
      1         0.001009857224 -0.000999999996 -0.000999999987
      2         0.001006435477 -0.000999999999 -0.001000000013
4     0         0.002183543791 -0.001499486759 -0.001499487165
      1         0.002880732585 -0.002052993033 -0.002052993199
      2         0.003562308026 -0.003012101758 -0.003012101188
5     0        -0.000000512917 -0.000000000000 -0.000000000000
      1         0.002052993199 -0.001999999958 -0.001999999958
      2         0.001012101270 -0.001000000042 -0.001000000042
6     0         0.006750561584 -0.006606952687 -0.006606953298
      1         0.005511237678 -0.005181139023 -0.005181139449
      2         0.009208617033 -0.008880067236 -0.008880067598
7     0         0.005406953299 -0.005146562321 -0.005146562872
      1         0.004181139437 -0.003749646460 -0.003749646802
      2         0.007880067609 -0.007467860298 -0.007467860594
8     0         0.003646562839 -0.003110104463 -0.003110104901
      1         0.002749646792 -0.002131238999 -0.002131239224
      2         0.005467860636 -0.004787920947 -0.004787921108
9     0         0.001110104952  0.000000529327  0.000000529090
      1         0.000131239153  0.000874361759  0.000874361741
      2         0.003787921127 -0.002885436296 -0.002885436317
10    0        -0.000000529090  0.000000000000 -0.000000000000
      1        -0.000652566677  0.000658101154  0.000658101185
      2         0.001663641254 -0.001658101113 -0.001658101185
11    0         0.009974590026 -0.009834331629 -0.009834331413
      1         0.015312563375 -0.014953336057 -0.014953337208
      2         0.001991500365 -0.001978174399 -0.001978174704
12    0         0.005970407068 -0.005923442788 -0.005923442599
      1         0.014953337208 -0.014594082266 -0.014594083319
      2         0.003842099049 -0.003742804945 -0.003742805248
13    0         0.000211299553 -0.000074277995 -0.000074278064
      1         0.005775060080 -0.005656687075 -0.005656687308
      2         0.000861714388 -0.000831715934 -0.000831715952
14    0        -0.001088719468  0.001110089879  0.001110089823
      1         0.002644356276 -0.002607693103 -0.002607693204
      2         0.001507044516 -0.001502396604 -0.001502396619
15    0         0.006111698019 -0.005863847743 -0.005863847474
      1         0.007631430052 -0.007059795429 -0.007059796076
      2         0.001669129075 -0.001417629665 -0.001417629929
16    0         0.004262385449 -0.003896876366 -0.003896876132
      1         0.005853666119 -0.005158545182 -0.005158545637
      2         0.001025221911 -0.000628243608 -0.000628243846
17    0         0.002757245740 -0.002665923867 -0.002665923820
      1         0.002723024115 -0.002687215621 -0.002687215781
      2        -0.000296604240  0.000353139602  0.000353139601
18    0         0.004223748076 -0.003820949549 -0.003820949550
      1         0.006932423305 -0.006530880199 -0.006530880199
      2         0.005244301825 -0.004848170252 -0.004848170251

                     pl_mw_mc       pl_mw_dss      ql_mvar_mc     ql_mvar_dss
index circuit
0     0        0.000204833782  0.000204833789  0.000512642343  0.000512642360
      1        0.000207446415  0.000207446424  0.000310865470  0.000310865488
      2        0.000034179843  0.000034179842  0.000067896325  0.000067896323
1     0        0.000215699560  0.000215699567  0.000507071329  0.000507071344
      1        0.000207090047  0.000207090056  0.000320756835  0.000320756853
      2        0.000047588528  0.000047588527  0.000111394314  0.000111394312
2     0        0.000211810140  0.000211810147  0.000525049881  0.000525049897
      1        0.000287249550  0.000287249563  0.000472084648  0.000472084673
      2        0.000054876095  0.000054876095  0.000109181083  0.000109181081
3     0        0.000000000772  0.000000000772 -0.000000520874 -0.000000520874
      1        0.000003610794  0.000003610794  0.000009857237  0.000009857237
      2        0.000005057120  0.000005057120  0.000006435464  0.000006435464

## Test 10: 20 bus grid with four controlled sgen, asymmetric load and sgen, voltage far below tolerance limits
This is to test possible interactions between controlled sgens located at different points of the grid. All controllers are expected to converge at valid operation points. 
Expecting controllers to increase voltage towards tolerance band by high reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [26]:
net = grids["twenty_bus_system_voltage_far_below_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
for i in [0,1,2,3]:
    check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=i, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (0.018)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (0.018)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (0.006333746452079356)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.8984, 0.8854, 0.9202] / [0.8722, 0.8758, 0.9292] / [0.9597, 0.9515, 0.9603] / [0.9963, 0.9966, 0.9946]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.010000, 0.015000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
p_mw: [0.010000, 0.015000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9560, 0.9444, 0.9766] / [0.9452, 0.9489, 0.9975] / [0.9692, 0.9611, 0.9698] / [0.9963, 0.9966, 0.9946]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.015483, 0.019098, 0.016492] / [0.015506, 0.017761, 0.018647] / [0.005675, 0.010354, 0.011809] / [0.005000, 0.005000, 0.005000]
p_mw: [0.010000, 0.015000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
q_mvar: [0.011821, 0.011821, 0.011821] / [0.014678, 0.014678, 0.014678] / [0.002685, 0.002685, 0.002685] / [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 1.4418629956658435e-08
Max overall va_degree difference: 7.017862314384615e-06
Max overall i_from_ka difference: 1.1918788273002079e-07
Max overall i_to_ka difference: 1.1918774572849955e-07
Max overall p_from_mw difference: 2.7180205752763698e-08
Max overall p_to_mw difference: 2.5430464338505043e-08
Max overall q_from_mvar difference: 1.212938819175613e-08
Max overall q_to_mvar difference: 1.2960906854708742e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999996154092 0.999996154091    0.000015969597    0.000015988960
      2     0.999996621887 0.999996621886 -119.999970814100 -119.999970801191
      3     0.999997407144 0.999997407143  120.000009798969  120.000009805419
1     0     0.000000017834 0.000000017834  -60.790467001490  -60.790467057631
...                    ...            ...               ...               ...
18    3     0.969909655053 0.969909655218  111.842817893651  111.842816257180
19    0     0.000000024211 0.000000024211  -70.282754634977  -70.282754779535
      1     0.961805356657 0.961805355390   -3.505458697145   -3.505458789337
      2     0.953629482395 0.953629480872 -123.234575565533 -123.234575655639
      3     0.966215475351 0.966215474244  117.450977955427  117.450977881554

[80 rows x 4 columns]

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.133702233473 0.133702234206 0.133702475030 0.133702475763
      1       0.139204453995 0.139204455212 0.139204694607 0.139204695825
      2       0.079295226336 0.079295226986 0.079295680384 0.079295681034
1     0       0.076115119591 0.076115119897 0.076115308008 0.076115308314
      1       0.085478979791 0.085478980608 0.085479068651 0.085479069468
      2       0.067669244313 0.067669244868 0.067669586051 0.067669586606
2     0       0.022546947459 0.022546947357 0.022546666855 0.022546666753
      1       0.027135838511 0.027135838884 0.027135685021 0.027135685394
      2       0.013497035990 0.013497036104 0.013497261425 0.013497261539
3     0       0.000002113434 0.000002113436 0.000000000035 0.000000000000
      1       0.014281609099 0.014281609123 0.014282275759 0.014282275783
      2       0.012057454553 0.012057454660 0.012058234746 0.012058234853
4     0       0.012669097675 0.012669098083 0.012670216549 0.012670216957
      1       0.012524811644 0.012524811621 0.012526361325 0.012526361302
      2       0.023618152429 0.023618152451 0.023619360770 0.023619360791
5     0       0.000002167361 0.000002167361 0.000000000000 0.000000000000
      1       0.031791110685 0.031791110910 0.031791711420 0.031791711645
      2       0.015912541098 0.015912541210 0.015913137946 0.015913138058
6     0       0.271250169466 0.271250288654 0.271250165387 0.271250284575
      1       0.206316446555 0.206316512062 0.206316391095 0.206316456603
      2       0.156623346264 0.156623411333 0.156622910227 0.156622975296
7     0       0.213552841397 0.213552949549 0.213552630215 0.213552738368
      1       0.153295213546 0.153295272928 0.153294965231 0.153295024613
      2       0.124017281249 0.124017343620 0.124016550944 0.124016613315
8     0       0.156426530082 0.156426618657 0.156426027157 0.156426115732
      1       0.100721857998 0.100721906201 0.100721298083 0.100721346286
      2       0.096495901428 0.096495959970 0.096494688450 0.096494746993
9     0       0.104341833488 0.104341902343 0.104340802410 0.104340871265
      1       0.056423383511 0.056423420812 0.056421985204 0.056422022505
      2       0.074198594210 0.074198647837 0.074196832130 0.074196885757
10    0       0.055279182224 0.055279209547 0.055279451798 0.055279479121
      1       0.055551362238 0.055551389824 0.055551631118 0.055551658704
      2       0.058452877019 0.058452904915 0.058453218856 0.058453246752
11    0       0.228006534078 0.228006566599 0.228006381970 0.228006414491
      1       0.184647515061 0.184647535183 0.184647858925 0.184647879047
      2       0.171086174742 0.171086198985 0.171086092083 0.171086116327
12    0       0.178527577054 0.178527607072 0.178527221706 0.178527251724
      1       0.127425686121 0.127425702995 0.127425925135 0.127425942009
      2       0.123900521535 0.123900543647 0.123900103391 0.123900125503
13    0       0.049271010150 0.049271016438 0.049271039446 0.049271045734
      1       0.045658619356 0.045658625607 0.045659789207 0.045659795458
      2       0.023118429259 0.023118431891 0.023118794698 0.023118797330
14    0       0.019592562404 0.019592565365 0.019592041646 0.019592044608
      1       0.025523226760 0.025523230098 0.025524182167 0.025524185505
      2       0.009607639448 0.009607640316 0.009609138562 0.009609139431
15    0       0.122460553086 0.122460576511 0.122459944601 0.122459968027
      1       0.079409074789 0.079409086193 0.079408556362 0.079408567765
      2       0.100565906460 0.100565926549 0.100565116876 0.100565136966
16    0       0.073650311600 0.073650330987 0.073649087918 0.073649107305
      1       0.044534789133 0.044534797188 0.044533318805 0.044533326859
      2       0.058864404315 0.058864420046 0.058863019843 0.058863035575
17    0       0.057884812064 0.057884821818 0.057885140935 0.057885150689
      1       0.046095595899 0.046095604245 0.046096195960 0.046096204306
      2       0.048981042591 0.048981050887 0.048981096631 0.048981104927
18    0       0.249253409105 0.249253411283 0.249253700086 0.249253702264
      1       0.252082270979 0.252082273213 0.252082699735 0.252082701968
      2       0.180917033649 0.180917035203 0.180917449379 0.180917450933

                     i_ka_mc       i_ka_dss   p_from_mw_mc  p_from_mw_dss  \
index circuit
0     0       0.133702475030 0.133702475763 0.030622637749 0.030622637704
      1       0.139204694607 0.139204695825 0.031887760452 0.031887760516
      2       0.079295680384 0.079295681034 0.017860080468 0.017860080475
1     0       0.076115308008 0.076115308314 0.017172127533 0.017172127475
      1       0.085479068651 0.085479069468 0.019253456814 0.019253456855
      2       0.067669586051 0.067669586606 0.015155292437 0.015155292439
2     0       0.022546947459 0.022546947357 0.005012642042 0.005012641979
      1       0.027135838511 0.027135838884 0.006027639162 0.006027639193
      2       0.013497261425 0.013497261539 0.003011635002 0.003011634997
3     0       0.000002113434 0.000002113436 0.000000000167 0.000000000175
      1       0.014282275759 0.014282275783 0.003004099566 0.003004099549
      2       0.012058234746 0.012058234853 0.002505551616 0.002505551618
4     0       0.012670216549 0.012670216957 0.002506783439 0.002506783498
      1       0.012526361325 0.012526361302 0.002025406084 0.002025406017
      2       0.023619360770 0.023619360791 0.004527216436 0.004527216445
5     0       0.000002167361 0.000002167361 0.000000000410 0.000000000410
      1       0.031791711420 0.031791711645 0.007022138257 0.007022138258
      2       0.015913137946 0.015913138058 0.003511976910 0.003511976911
6     0       0.271250169466 0.271250288654 0.062609866454 0.062609893635
      1       0.206316446555 0.206316512062 0.047646557925 0.047646572724
      2       0.156623346264 0.156623411333 0.035600821554 0.035600835727
7     0       0.213552841397 0.213552949549 0.047674536196 0.047674559210
      1       0.153295213546 0.153295272928 0.034205896055 0.034205908464
      2       0.124017281249 0.124017343620 0.026802109710 0.026802122374
8     0       0.156426530082 0.156426618657 0.033469855300 0.033469872375
      1       0.100721857998 0.100721906201 0.021406518059 0.021406527091
      2       0.096495901428 0.096495959970 0.018298605882 0.018298616424
9     0       0.104341833488 0.104341902343 0.019814272355 0.019814282211
      1       0.056423383511 0.056423420812 0.009062321254 0.009062326135
      2       0.074198594210 0.074198647837 0.009992261007 0.009992268912
10    0       0.055279451798 0.055279479121 0.011957974509 0.011957980291
      1       0.055551631118 0.055551658704 0.012060679229 0.012060684964
      2       0.058453218856 0.058453246752 0.013268084690 0.013268091006
11    0       0.228006534078 0.228006566599 0.052610975464 0.052610982542
      1       0.184647858925 0.184647879047 0.041924641493 0.041924645795
      2       0.171086174742 0.171086198985 0.039505837875 0.039505843188
12    0       0.178527577054 0.178527607072 0.039746691259 0.039746697303
      1       0.127425925135 0.127425942009 0.028228968269 0.028228971742
      2       0.123900521535 0.123900543647 0.027608490187 0.027608494738
13    0       0.049271039446 0.049271045734 0.010910761027 0.010910762312
      1       0.045659789207 0.045659795458 0.008163614431 0.008163615447
      2       0.023118794698 0.023118797330 0.005110856980 0.005110857511
14    0       0.019592562404 0.019592565365 0.004173074308 0.004173074872
      1       0.025524182167 0.025524185505 0.004851471948 0.004851472500
      2       0.009609138562 0.009609139431 0.001509281646 0.001509281809
15    0       0.122460553086 0.122460576511 0.026060605730 0.026060609933
      1       0.079409074789 0.079409086193 0.016853797061 0.016853799137
      2       0.100565906460 0.100565926549 0.021083954335 0.021083958114
16    0       0.073650311600 0.073650330987 0.013168942172 0.013168944656
      1       0.044534789133 0.044534797188 0.006798593157 0.006798593935
      2       0.058864404315 0.058864420046 0.010091614333 0.010091616639
17    0       0.057885140935 0.057885150689 0.012606942335 0.012606944364
      1       0.046096195960 0.046096204306 0.009588066451 0.009588068002
      2       0.048981096631 0.048981104927 0.011041225382 0.011041227187
18    0       0.249253700086 0.249253702264 0.056764061531 0.056764061621
      1       0.252082699735 0.252082701968 0.056681074064 0.056681074155
      2       0.180917449379 0.180917450933 0.040791353365 0.040791353423

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       -0.030172127673 -0.030172127615  0.003955846662
      1       -0.031253456887 -0.031253456929  0.004080526800
      2       -0.017655292392 -0.017655292393  0.004044940911
1     0       -0.017012642050 -0.017012641988  0.001693075358
      1       -0.019027639191 -0.019027639224  0.000990901540
      2       -0.015011634966 -0.015011634962  0.002619613341
2     0       -0.005000000203 -0.005000000139 -0.000654804692
      1       -0.006004099581 -0.006004099611 -0.000432344237
      2       -0.003005551609 -0.003005551604  0.000334251444
3     0        0.000000000008  0.000000000000 -0.000000473059
      1       -0.003000000028 -0.003000000011  0.001011382089
      2       -0.002500000004 -0.002500000005  0.001006987149
4     0       -0.002500000426 -0.002500000485  0.001508738870
      1       -0.002022138325 -0.002022138258  0.002064975095
      2       -0.004511976941 -0.004511976951  0.003042105208
5     0        0.000000000000  0.000000000000 -0.000000498676
      1       -0.007000000076 -0.007000000076  0.002054749745
      2       -0.003500000000 -0.003500000000  0.001012489241
6     0       -0.060674533867 -0.060674559297  0.002015621342
      1       -0.046205894696 -0.046205908500 -0.000047650101
      2       -0.034802108765 -0.034802122296 -0.006394368075
7     0       -0.046469850734 -0.046469872492 -0.003499769462
      1       -0.033406515373 -0.033406527117 -0.003454036989
      2       -0.026298604162 -0.026298616338 -0.009020535461
8     0       -0.032814265991 -0.032814282294 -0.007672197707
      1       -0.021062317508 -0.021062326193 -0.005780308335
      2       -0.017992258632 -0.017992268822 -0.012035562102
9     0       -0.019518219951 -0.019518229391 -0.011109059755
      1       -0.008951522885 -0.008951527612 -0.008351675434
      2       -0.009816991585 -0.009816999258 -0.013638214102
10    0       -0.011866302109 -0.011866307799  0.001619439785
      1       -0.011968101373 -0.011968107015  0.001652671289
      2       -0.013165578954 -0.013165585170  0.002300009185
11    0       -0.051040633838 -0.051040640425 -0.002168613167
      1       -0.040869622440 -0.040869626498  0.007790791494
      2       -0.038673891774 -0.038673896853 -0.000610674303
12    0       -0.038784338541 -0.038784344233 -0.005838427244
      1       -0.027719458330 -0.027719461662  0.003754259732
      2       -0.027179792156 -0.027179796557 -0.005017472267
13    0       -0.010837932555 -0.010837933820  0.000212481300
      1       -0.008101071099 -0.008101072096  0.005742661332
      2       -0.005094822733 -0.005094823260  0.000912587757
14    0       -0.004161559115 -0.004161559675 -0.001076841780
      1       -0.004831927735 -0.004831928282  0.002613747440
      2       -0.001506511875 -0.001506512037  0.001529390442
15    0       -0.025609419728 -0.025609423743 -0.007517771878
      1       -0.016645502342 -0.016645504353 -0.004157775925
      2       -0.020804223450 -0.020804227121 -0.008093533939
16    0       -0.013011800873 -0.013011803267 -0.009445531415
      1       -0.006726392375 -0.006726393123 -0.006887138880
      2       -0.009998040904 -0.009998043163 -0.008513452266
17    0       -0.012506423290 -0.012506425283  0.002091779271
      1       -0.009524320603 -0.009524322130  0.003022427678
      2       -0.010969250793 -0.010969252573  0.000356896034
18    0       -0.055055882623 -0.055055882656  0.009553525425
      1       -0.054681331984 -0.054681332008  0.013278734757
      2       -0.039762785623 -0.039762785647  0.009039267604

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss       pl_mw_mc  \
index circuit
0     0         0.003955846691 -0.002893075167 -0.002893075168 0.000450510076
      1         0.004080526789 -0.002990901749 -0.002990901701 0.000634303566
      2         0.004044940991 -0.003619613323 -0.003619613388 0.000204788076
1     0         0.001693075359 -0.001345195272 -0.001345195265 0.000159485483
      1         0.000990901492 -0.000567655788 -0.000567655725 0.000225817623
      2         0.002619613407 -0.002334251454 -0.002334251510 0.000143657472
2     0        -0.000654804700  0.000685109956  0.000685109964 0.000012641839
      1        -0.000432344300  0.000473254749  0.000473254814 0.000023539581
      2         0.000334251500 -0.000322350287 -0.000322350343 0.000006083393
3     0        -0.000000473060 -0.000000000000  0.000000000000 0.000000000175
      1         0.001011382077 -0.000999999997 -0.000999999985 0.000004099537
      2         0.001006987151 -0.001000000013 -0.001000000015 0.000005551612
4     0         0.001508738915 -0.001499501364 -0.001499501409 0.000006783013
      1         0.002064975125 -0.002054749716 -0.002054749746 0.000003267759
      2         0.003042105136 -0.003012489230 -0.003012489157 0.000015239494
5     0        -0.000000498676  0.000000000000 -0.000000000000 0.000000000410
      1         0.002054749746 -0.001999999956 -0.001999999956 0.000022138181
      2         0.001012489242 -0.001000000044 -0.001000000044 0.000011976910
6     0         0.002015619204  0.002299769596  0.002299775527 0.001935332588
      1        -0.000047653731  0.002454036667  0.002454041879 0.001440663229
      2        -0.006394372770  0.008020535638  0.008020541735 0.000798712789
7     0        -0.003499775431  0.006172198286  0.006172206959 0.001204685462
      1        -0.003454041993  0.004780307910  0.004780313976 0.000799380682
      2        -0.009020541716  0.010035562742  0.010035570048 0.000503505547
8     0        -0.007672206862  0.009109061227  0.009109072008 0.000655589309
      1        -0.005780314113  0.006351675376  0.006351681725 0.000344200552
      2        -0.012035570005  0.012638214781  0.012638223432 0.000306347250
9     0        -0.011109071885  0.011740157539  0.011740170500 0.000296052404
      1        -0.008351681846  0.008528948880  0.008528955544 0.000110798370
      2        -0.013638223431  0.013992689583  0.013992699432 0.000175269423
10    0         0.001619440504 -0.001436538666 -0.001436539200 0.000091672399
      1         0.001652672843 -0.001467958916 -0.001467960283 0.000092577855
      2         0.002300010906 -0.002095498991 -0.002095500513 0.000102505736
11    0        -0.002168615070  0.005223145153  0.005223147964 0.001570341626
      1         0.007790792185 -0.005703841929 -0.005703842111 0.001055019052
      2        -0.000610675354  0.002382336647  0.002382338222 0.000831946101
12    0        -0.005838429998  0.007699695196  0.007699698597 0.000962352718
      1         0.003754259847 -0.002751811616 -0.002751811436 0.000509509939
      2        -0.005017473923  0.005953467875  0.005953469876 0.000428698031
13    0         0.000212481126 -0.000067282233 -0.000067282020 0.000072828472
      1         0.005742662020 -0.005618019989 -0.005618020641 0.000062543332
      2         0.000912587890 -0.000880993476 -0.000880993601 0.000016034247
14    0        -0.001076842012  0.001099418006  0.001099418245 0.000011515193
      1         0.002613747747 -0.002575095989 -0.002575096286 0.000019544213
      2         0.001529390527 -0.001524321873 -0.001524321957 0.000002769771
15    0        -0.007517775028  0.008382170184  0.008382173672 0.000451186002
      1        -0.004157776902  0.004547848689  0.004547849792 0.000208294719
      2        -0.008093536142  0.008716104316  0.008716106775 0.000279730886
16    0        -0.009445535010  0.009750262421  0.009750266178 0.000157141299
      1        -0.006887140376  0.007006221435  0.007006222979 0.000072200782
      2        -0.008513454851  0.008734088453  0.008734091158 0.000093573429
17    0         0.002091779665 -0.001891193239 -0.001891193562 0.000100519045
      1         0.003022428385 -0.002895380890 -0.002895381548 0.000063745848
      2         0.000356896366 -0.000213424605 -0.000213424886 0.000071974589
18    0         0.009553525551 -0.005833724466 -0.005833724467 0.001708178908
      1         0.013278734883 -0.009593419152 -0.009593419153 0.001999742080
      2         0.009039267682 -0.006972856371 -0.006972856379 0.001028567742


## Test 11: 20 bus grid with four controlled sgen, asymmetric load and sgen, voltage below tolerance limits
This is to test possible interactions between controlled sgens located at different points of the grid. All controllers are expected to converge at valid operation points. 
Expecting controllers to increase voltage towards tolerance band by reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [27]:
net = grids["twenty_bus_system_voltage_below_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
for i in [0,1,2,3]:
    check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=i, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (0.011873445629737798)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (0.005467579933725387)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9585, 0.9243, 0.9652] / [0.9619, 0.9559, 0.9684] / [0.9897, 0.9944, 1.0106] / [0.9963, 0.9966, 0.9946]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.030000, 0.020000, 0.030000] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
p_mw: [0.030000, 0.020000, 0.030000] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9783, 0.9448, 0.9849] / [0.9711, 0.9651, 0.9776] / [0.9897, 0.9944, 1.0106] / [0.9963, 0.9966, 0.9946]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.030289, 0.020432, 0.030289] / [0.005369, 0.010189, 0.011665] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
p_mw: [0.030000, 0.020000, 0.030000] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.010000, 0.011500] / [0.005000, 0.005000, 0.005000]
q_mvar: [0.004177, 0.004177, 0.004177] / [0.001955, 0.001955, 0.001955] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 5.846775319451325e-08
Max overall va_degree difference: 4.283509799307694e-06
Max overall i_from_ka difference: 4.269913474186371e-08
Max overall i_to_ka difference: 4.269681908031231e-08
Max overall p_from_mw difference: 1.0216731492068698e-08
Max overall p_to_mw difference: 9.91356349094863e-09
Max overall q_from_mvar difference: 2.0111773157288366e-08
Max overall q_to_mvar difference: 2.0539841916547303e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     0.999998193970 0.999998193970    0.000018038151    0.000018057498
      2     0.999998379947 0.999998379947 -119.999974237590 -119.999974224668
      3     0.999998937960 0.999998937960  120.000019484687  120.000019491142
1     0     0.000000005040 0.000000005040   98.562207210190   98.562207235044
...                    ...            ...               ...               ...
18    3     0.978158114999 0.978158130905  118.185724300552  118.185724716148
19    0     0.000000001000 0.000000001000 -122.681424523321 -122.681424827329
      1     0.979018884349 0.979018883587   -1.889064516583   -1.889064563676
      2     0.973788726543 0.973788725595 -121.983481849693 -121.983481907110
      3     0.975356067434 0.975356066555  118.330862063251  118.330862010967

[80 rows x 4 columns]

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.023557785989 0.023557786258 0.023558607368 0.023558607637
      1       0.015828083372 0.015828084629 0.015829335896 0.015829337153
      2       0.029165394658 0.029165395444 0.029166093228 0.029166094014
1     0       0.023558607368 0.023558607637 0.023559422183 0.023559422453
      1       0.015829335896 0.015829337153 0.015830573631 0.015830574887
      2       0.038780690109 0.038780691199 0.038780962524 0.038780963614
2     0       0.023559422183 0.023559422453 0.023560231553 0.023560231822
      1       0.030780649458 0.030780650371 0.030780965582 0.030780966495
      2       0.038780962524 0.038780963614 0.038781221466 0.038781222556
3     0       0.000002159119 0.000002159119 0.000000000005 0.000000000000
      1       0.013800738214 0.013800738244 0.013801424420 0.013801424451
      2       0.011567562550 0.011567562618 0.011568373691 0.011568373759
4     0       0.012669071637 0.012669072046 0.012670190514 0.012670190922
      1       0.012524788596 0.012524788573 0.012526338279 0.012526338256
      2       0.023618115626 0.023618115648 0.023619323969 0.023619323991
5     0       0.000002167365 0.000002167365 0.000000000000 0.000000000000
      1       0.031791053807 0.031791054032 0.031791654542 0.031791654768
      2       0.015912516256 0.015912516368 0.015913113105 0.015913113217
6     0       0.152097855634 0.152097866364 0.152098105350 0.152098116080
      1       0.133656473475 0.133656479512 0.133656617982 0.133656624019
      2       0.070896193771 0.070896195239 0.070896907549 0.070896909017
7     0       0.094400023508 0.094400031584 0.094400216512 0.094400224589
      1       0.080341627460 0.080341631720 0.080341672919 0.080341677179
      2       0.036880663374 0.036880663922 0.036881717710 0.036881718257
8     0       0.035977184985 0.035977188660 0.035977220408 0.035977224083
      1       0.026674280681 0.026674282133 0.026673990777 0.026673992228
      2       0.009919614256 0.009919613323 0.009921605574 0.009921604642
9     0       0.023939539890 0.023939541854 0.023938769951 0.023938771914
      1       0.030610523817 0.030610526157 0.030609635024 0.030609637364
      2       0.039332381399 0.039332382514 0.039332644089 0.039332645204
10    0       0.000002123816 0.000002123816 0.000000000000 0.000000000000
      1       0.010742967232 0.010742967715 0.010742359531 0.010742360014
      2       0.010740868700 0.010740869183 0.010742359531 0.010742360014
11    0       0.103376754872 0.103376782583 0.103377147571 0.103377175281
      1       0.108997019454 0.108997048459 0.108997873534 0.108997902540
      2       0.060729831069 0.060729836154 0.060729768871 0.060729773956
12    0       0.082486994082 0.082487036781 0.082486981625 0.082487024322
      1       0.108997873534 0.108997902540 0.108998671876 0.108998700882
      2       0.036694693748 0.036694697267 0.036695026022 0.036695029540
13    0       0.048597751212 0.048597765394 0.048597800806 0.048597814988
      1       0.044921828542 0.044921842843 0.044922993570 0.044923007871
      2       0.022850426028 0.022850429917 0.022850798021 0.022850801911
14    0       0.019238549937 0.019238557746 0.019238042155 0.019238049964
      1       0.025158667206 0.025158674051 0.025159612514 0.025159619359
      2       0.009567146621 0.009567147859 0.009568668690 0.009568669927
15    0       0.025866983674 0.025867012310 0.025866869191 0.025866897821
      1       0.052865766219 0.052865774427 0.052866140261 0.052866148470
      2       0.010272424092 0.010272424654 0.010271589821 0.010271590383
16    0       0.030811092574 0.030811099869 0.030810610381 0.030810617669
      1       0.007208473172 0.007208465360 0.007208339750 0.007208331946
      2       0.037857109462 0.037857118899 0.037856909048 0.037856918485
17    0       0.057232284205 0.057232297011 0.057232647427 0.057232660233
      1       0.045344549310 0.045344561372 0.045345101707 0.045345113769
      2       0.048353250317 0.048353259477 0.048353321654 0.048353330815
18    0       0.133358303475 0.133358305102 0.133358541028 0.133358542655
      1       0.148608459187 0.148608461048 0.148608865924 0.148608867785
      2       0.130153637882 0.130153639459 0.130154154099 0.130154155676

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       0.023558607368 0.023558607637  0.005034778712  0.005034778751
      1       0.015829335896 0.015829337153 -0.002981164082 -0.002981164192
      2       0.029166093228 0.029166094014 -0.006374175615 -0.006374175839
1     0       0.023559422183 0.023559422453  0.005022209682  0.005022209721
      1       0.015830573631 0.015830574887 -0.002983485684 -0.002983485796
      2       0.038780962524 0.038780963614 -0.008899266474 -0.008899266702
2     0       0.023560231553 0.023560231822  0.005012696115  0.005012696153
      1       0.030780965582 0.030780966495 -0.006986625589 -0.006986625702
      2       0.038781221466 0.038781222556 -0.008943363941 -0.008943364172
3     0       0.000002159119 0.000002159119 -0.000000001114 -0.000000001115
      1       0.013801424420 0.013801424451  0.003003860538  0.003003860519
      2       0.011568373691 0.011568373759  0.002505120334  0.002505120334
4     0       0.012670190514 0.012670190922  0.002506783412  0.002506783472
      1       0.012526338279 0.012526338256  0.002025405990  0.002025405922
      2       0.023619323969 0.023619323991  0.004527216350  0.004527216360
5     0       0.000002167365 0.000002167365  0.000000000410  0.000000000410
      1       0.031791654542 0.031791654768  0.007022138176  0.007022138177
      2       0.015913113105 0.015913113217  0.003511976872  0.003511976872
6     0       0.152098105350 0.152098116080  0.034813122651  0.034813124865
      1       0.133656617982 0.133656624019  0.030762900705  0.030762901894
      2       0.070896907549 0.070896909017  0.015395928206  0.015395928498
7     0       0.094400216512 0.094400224589  0.021250462213  0.021250463857
      1       0.080341672919 0.080341677179  0.018122184624  0.018122185436
      2       0.036881717710 0.036881718257  0.007256133850  0.007256134029
8     0       0.035977220408 0.035977224083  0.008043048166  0.008043048912
      1       0.026674280681 0.026674282133  0.005879360362  0.005879360607
      2       0.009921605574 0.009921604642 -0.000773691019 -0.000773691026
9     0       0.023939539890 0.023939541854 -0.004981037036 -0.004981037313
      1       0.030610523817 0.030610526157 -0.006152034372 -0.006152034755
      2       0.039332644089 0.039332645204 -0.008772139020 -0.008772139242
10    0       0.000002123816 0.000002123816 -0.000000001265 -0.000000001265
      1       0.010742967232 0.010742967715  0.002289916110  0.002289916187
      2       0.010742359531 0.010742360014  0.001717008616  0.001717008692
11    0       0.103377147571 0.103377175281  0.023416507447  0.023416517664
      1       0.108997873534 0.108997902540  0.023012673436  0.023012676402
      2       0.060729831069 0.060729836154  0.014021953041  0.014021954118
12    0       0.082486994082 0.082487036781  0.018723901498  0.018723911429
      1       0.108998671876 0.108998700882  0.022657744610  0.022657747421
      2       0.036695026022 0.036695029540  0.008288716394  0.008288717242
13    0       0.048597800806 0.048597814988  0.010919058712  0.010919062125
      1       0.044922993570 0.044923007871  0.008156762031  0.008156764075
      2       0.022850798021 0.022850801911  0.005104069840  0.005104070654
14    0       0.019238549937 0.019238557746  0.004172781061  0.004172782830
      1       0.025159612514 0.025159619359  0.004852677473  0.004852678490
      2       0.009568668690 0.009568669927  0.001507377429  0.001507377887
15    0       0.025866983674 0.025867012310  0.005808016620  0.005808022216
      1       0.052866140261 0.052866148470  0.011441211589  0.011441211865
      2       0.010272424092 0.010272424654  0.002147196497  0.002147196285
16    0       0.030811092574 0.030811099869 -0.006732658717 -0.006732655973
      1       0.007208473172 0.007208465360  0.001569441580  0.001569440161
      2       0.037857109462 0.037857118899 -0.008540545644 -0.008540547677
17    0       0.057232647427 0.057232660233  0.012717508830  0.012717512394
      1       0.045345101707 0.045345113769  0.009523774984  0.009523776829
      2       0.048353321654 0.048353330815  0.010988801234  0.010988803401
18    0       0.133358541028 0.133358542655  0.030550222858  0.030550223017
      1       0.148608865924 0.148608867785  0.033582862412  0.033582862595
      2       0.130154154099 0.130154155676  0.029071159320  0.029071159467

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0       -0.005022209682 -0.005022209721  0.002061372953
      1        0.002983485684  0.002983485796  0.002115212246
      2        0.006399266461  0.006399266688  0.002176281826
1     0       -0.005012696115 -0.005012696153  0.002039436849
      1        0.002986625557  0.002986625670  0.002094866903
      2        0.008943363941  0.008943364172  0.001140105929
2     0       -0.004999999046 -0.004999999084  0.002017724402
      1        0.006996139366  0.006996139481  0.001072623950
      2        0.008994879431  0.008994879666  0.001072061758
3     0       -0.000000000001 -0.000000000000 -0.000000493492
      1       -0.003000000029 -0.003000000010  0.001010570426
      2       -0.002500000004 -0.002500000005  0.001006382474
4     0       -0.002500000426 -0.002500000485  0.001508738827
      1       -0.002022138244 -0.002022138177  0.002064974855
      2       -0.004511976903 -0.004511976912  0.003042105068
5     0        0.000000000000 -0.000000000000 -0.000000498678
      1       -0.007000000076 -0.007000000076  0.002054749546
      2       -0.003500000000 -0.003500000000  0.001012489198
6     0       -0.034250461811 -0.034250463940  0.004673591941
      1       -0.030122184356 -0.030122185471  0.002527915014
      2       -0.015256133672 -0.015256133956  0.005570689168
7     0       -0.021043047413 -0.021043049019  0.002152883131
      1       -0.017879359850 -0.017879360630  0.000532652980
      2       -0.007226308720 -0.007226308898  0.004201795402
8     0       -0.008018962014 -0.008018962754  0.000154023719
      1       -0.005847965055 -0.005847965297 -0.000821189256
      2        0.000772139311  0.000772139318  0.002095800630
9     0        0.005000000985  0.005000001264 -0.001914205603
      1        0.006171192954  0.006171193341 -0.002855504706
      2        0.008821881552  0.008821881779  0.001091897698
10    0        0.000000000000 -0.000000000000 -0.000000476305
      1       -0.002286455306 -0.002286455383 -0.000699321737
      2       -0.001713544541 -0.001713544616  0.001712224509
11    0       -0.023126475311 -0.023126485224  0.004650302348
      1       -0.022657744610 -0.022657747421  0.010199681219
      2       -0.013886142335 -0.013886143445 -0.000289386983
12    0       -0.018539938327 -0.018539947943  0.000129435871
      1       -0.022302809970 -0.022302812628  0.009532554853
      2       -0.008233565783 -0.008233566650  0.001338546348
13    0       -0.010848205684 -0.010848209054  0.000342052426
      1       -0.008096222113 -0.008096224117  0.005595013833
      2       -0.005088405228 -0.005088406037  0.000919924538
14    0       -0.004161677009 -0.004161678769 -0.001018349391
      1       -0.004833688780 -0.004833689786  0.002531824542
      2       -0.001504630990 -0.001504631447  0.001550810144
15    0       -0.005793989262 -0.005793994766 -0.000278847094
      1       -0.011362281370 -0.011362281623  0.002144293061
      2       -0.002139960321 -0.002139960120 -0.000908557918
16    0        0.006771021570  0.006771018834 -0.001566370349
      1       -0.001569232754 -0.001569231329 -0.000106719331
      2        0.008568117768  0.008568119851 -0.000768995233
17    0       -0.012619240759 -0.012619244278  0.002335740322
      1       -0.009462091943 -0.009462093755  0.002681830805
      2       -0.010918659827 -0.010918661965  0.000441205980
18    0       -0.030018808766 -0.030018808903  0.003896637337
      1       -0.032921470169 -0.032921470324  0.007072918270
      2       -0.028559720647 -0.028559720773  0.007637462054

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss  \
index circuit
0     0         0.002061372924 -0.002039436849 -0.002039436819
      1         0.002115212549 -0.002094866903 -0.002094867202
      2         0.002176281588 -0.002140105929 -0.002140105687
1     0         0.002039436819 -0.002017724402 -0.002017724370
      1         0.002094867202 -0.002072623950 -0.002072624245
      2         0.001140105687 -0.001072061758 -0.001072061510
2     0         0.002017724370 -0.001999506541 -0.001999506508
      1         0.001072624245 -0.001010570138 -0.001010570428
      2         0.001072061510 -0.001006382730 -0.001006382476
3     0        -0.000000493492  0.000000000000  0.000000000000
      1         0.001010570428 -0.000999999985 -0.000999999987
      2         0.001006382476 -0.001000000011 -0.001000000013
4     0         0.001508738872 -0.001499501362 -0.001499501407
      1         0.002064974885 -0.002054749517 -0.002054749547
      2         0.003042104995 -0.003012489187 -0.003012489114
5     0        -0.000000498678  0.000000000000 -0.000000000000
      1         0.002054749547 -0.001999999956 -0.001999999956
      2         0.001012489198 -0.001000000044 -0.001000000044
6     0         0.004673592269 -0.003352882993 -0.003352883117
      1         0.002527914997 -0.001532653088 -0.001532652969
      2         0.005570689028 -0.005201795367 -0.005201795201
7     0         0.002152883207 -0.001654023513 -0.001654023496
      1         0.000532652861 -0.000178810857 -0.000178810697
      2         0.004201795219 -0.004095800537 -0.004095800347
8     0         0.000154023581 -0.000085794097 -0.000085793943
      1        -0.000821189427  0.000855504677  0.000855504852
      2         0.002095800386 -0.002091897666 -0.002091897423
9     0        -0.001914205952  0.001955327750  0.001955328107
      1        -0.002855504955  0.002908089943  0.002908090201
      2         0.001091897422 -0.001011289666 -0.001011289383
10    0        -0.000000476305  0.000000000000 -0.000000000000
      1        -0.000699321779  0.000705780328  0.000705780371
      2         0.001712224564 -0.001705780316 -0.001705780371
11    0         0.004650282920 -0.003979491171 -0.003979471383
      1         0.010199690636 -0.009532554853 -0.009532563787
      2        -0.000289387054  0.000511509596  0.000511509672
12    0         0.000129415759  0.000305994536  0.000306015076
      1         0.009532563787 -0.008865395358 -0.008865403809
      2         0.001338545953 -0.001254477953 -0.001254477569
13    0         0.000342052005 -0.000200821300 -0.000200820794
      1         0.005595015840 -0.005474384280 -0.005474386208
      2         0.000919924996 -0.000889078180 -0.000889078627
14    0        -0.001018349820  0.001040086392  0.001040086839
      1         0.002531825364 -0.002494289221 -0.002494290021
      2         0.001550810086 -0.001545796878 -0.001545796818
15    0        -0.000278867102  0.000327386848  0.000327406962
      1         0.002144299308 -0.001998439814 -0.001998445958
      2        -0.000908558746  0.000913139703  0.000913140528
16    0        -0.001566390449  0.001614736580  0.001614756741
      1        -0.000106714116  0.000106717423  0.000106712208
      2        -0.000768996967  0.000851506494  0.000851508296
17    0         0.002335740719 -0.002139684241 -0.002139684548
      1         0.002681832263 -0.002558906796 -0.002558908186
      2         0.000441207293 -0.000301406008 -0.000301407265
18    0         0.003896637399 -0.002827349729 -0.002827349748
      1         0.007072918350 -0.005751996442 -0.005751996467
      2         0.007637462120 -0.006620653759 -0.006620653785

                     pl_mw_mc       pl_mw_dss      ql_mvar_mc     ql_mvar_dss
index circuit
0     0        0.000012569030  0.000012569030  0.000021936104  0.000021936105
      1        0.000002321602  0.000002321603  0.000020345344  0.000020345347
      2        0.000025090847  0.000025090849  0.000036175897  0.000036175900
1     0        0.000009513567  0.000009513568  0.000021712448  0.000021712449
      1        0.000003139873  0.000003139874  0.000022242953  0.000022242956
      2        0.000044097467  0.000044097470  0.000068044171  0.000068044177
2     0        0.000012697068  0.000012697069  0.000018217861  0.000018217862
      1        0.000009513777  0.000009513779  0.000062053812  0.000062053817
      2        0.000051515490  0.000051515494  0.000065679028  0.000065679034

## Test 12: 20 bus grid with four controlled sgen, asymmetric load and sgen, voltage above tolerance limits
This is to test possible interactions between controlled sgens located at different points of the grid. All controllers are expected to converge at valid operation points. 
Expecting controllers to decrease voltage towards tolerance band by reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [28]:
net = grids["twenty_bus_system_voltage_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
for i in [0,1,2,3]:
    check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=i, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.0012257879739967276)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.0017210964231370652)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.005007593227706826)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9912, 1.0085, 1.0280] / [1.0222, 1.0356, 1.0340] / [1.0290, 1.0255, 1.0414] / [1.0097, 1.0139, 1.0125]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.040000, 0.045000, 0.035000] / [0.030000, 0.040000, 0.035000] / [0.030000, 0.030000, 0.035000] / [0.030000, 0.040000, 0.035000]
p_mw: [0.040000, 0.045000, 0.035000] / [0.030000, 0.040000, 0.035000] / [0.030000, 0.030000, 0.035000] / [0.030000, 0.040000, 0.035000]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9894, 1.0067, 1.0263] / [1.0198, 1.0332, 1.0316] / [1.0226, 1.0191, 1.0351] / [1.0097, 1.0139, 1.0125]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.040002, 0.045002, 0.035002] / [0.030005, 0.040004, 0.035004] / [0.030061, 0.030061, 0.035052] / [0.030000, 0.040000, 0.035000]
p_mw: [0.040000, 0.045000, 0.035000] / [0.030000, 0.040000, 0.035000] / [0.030000, 0.030000, 0.035000] / [0.030000, 0.040000, 0.035000]
q_mvar: [-0.000379, -0.000379, -0.000379] / [-0.000538, -0.000538, -0.000538] / [-0.001911, -0.001911, -0.001911] / [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 3.130768855275079e-08
Max overall va_degree difference: 5.013474307702381e-06
Max overall i_from_ka difference: 8.85336366995837e-08
Max overall i_to_ka difference: 8.853352168047834e-08
Max overall p_from_mw difference: 1.742680708072264e-08
Max overall p_to_mw difference: 1.8104820677378175e-08
Max overall q_from_mvar difference: 1.3135199775082818e-08
Max overall q_to_mvar difference: 1.2050234376309588e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.000000621961 1.000000621961    0.000032272850    0.000032292221
      2     1.000001437019 1.000001437020 -119.999956121993 -119.999956109062
      3     1.000001122723 1.000001122723  120.000030929201  120.000030935664
1     0     0.000000005004 0.000000005004  100.140536602155  100.140536712768
...                    ...            ...               ...               ...
18    3     1.022778614224 1.022778609942  123.930400168079  123.930401257849
19    0     0.000000005203 0.000000005203  108.009231704506  108.009231668522
      1     0.984472669218 0.984472668742   -1.063819635464   -1.063819648267
      2     0.982769162076 0.982769161549 -120.944477937587 -120.944477953287
      3     0.984331032046 0.984331031568  119.001176759313  119.001176735445

[80 rows x 4 columns]

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.086293057459 0.086293055773 0.086293609314 0.086293607628
      1       0.099215345026 0.099215347570 0.099215884583 0.099215887127
      2       0.126705390919 0.126705395859 0.126705873520 0.126705878460
1     0       0.086293609314 0.086293607628 0.086294111368 0.086294109683
      1       0.099215884583 0.099215887127 0.099216363339 0.099216365883
      2       0.136485686712 0.136485691815 0.136485999747 0.136486004850
2     0       0.086294111368 0.086294109683 0.086294562720 0.086294561035
      1       0.115379309632 0.115379312149 0.115379578476 0.115379580993
      2       0.136485999747 0.136486004850 0.136486242522 0.136486247625
3     0       0.000002230907 0.000002230906 0.000000000016 0.000000000000
      1       0.013465048443 0.013465048606 0.013465753609 0.013465753772
      2       0.011292416226 0.011292416363 0.011293247352 0.011293247489
4     0       0.096702255710 0.096702253765 0.096702430311 0.096702428365
      1       0.141109809357 0.141109814941 0.141109985498 0.141109991082
      2       0.109761457374 0.109761457310 0.109761746670 0.109761746606
5     0       0.000002196491 0.000002196491 0.000000000000 0.000000000000
      1       0.031240704612 0.031240704817 0.031241314174 0.031241314380
      2       0.015628674041 0.015628674128 0.015629281259 0.015629281345
6     0       0.041862163073 0.041862170812 0.041863742817 0.041863750556
      1       0.094693823119 0.094693842590 0.094694504639 0.094694524110
      2       0.092236065308 0.092236077302 0.092237099742 0.092237111736
7     0       0.056515692246 0.056515699276 0.056516630335 0.056516637364
      1       0.106079282559 0.106079302038 0.106079748655 0.106079768134
      2       0.100202305560 0.100202317631 0.100203120830 0.100203132901
8     0       0.085520748303 0.085520755502 0.085521159813 0.085521167012
      1       0.122341923340 0.122341943557 0.122342191078 0.122342211295
      2       0.122449687969 0.122449700924 0.122450150777 0.122450163733
9     0       0.127405898646 0.127405907817 0.127405966551 0.127405975722
      1       0.151582213457 0.151582236161 0.151582237452 0.151582260155
      2       0.136448122949 0.136448136919 0.136448404189 0.136448418159
10    0       0.000002222146 0.000002222146 0.000000000000 0.000000000000
      1       0.009989440861 0.009989442015 0.009988832035 0.009988833189
      2       0.009987274392 0.009987275547 0.009988832035 0.009988833189
11    0       0.051515112056 0.051515109845 0.051517169793 0.051517167583
      1       0.111524701951 0.111524790484 0.111526161292 0.111526249826
      2       0.028360556673 0.028360565146 0.028361400197 0.028361408672
12    0       0.047535523272 0.047535508601 0.047536949474 0.047536934803
      1       0.111526161292 0.111526249826 0.111527564583 0.111527653116
      2       0.053969966632 0.053969974321 0.053970714719 0.053970722409
13    0       0.047589601401 0.047589607331 0.047589631009 0.047589636940
      1       0.044303288129 0.044303292740 0.044304506807 0.044304511418
      2       0.022465054636 0.022465055853 0.022465400750 0.022465401967
14    0       0.018981635519 0.018981637988 0.018981088027 0.018981090495
      1       0.024767569555 0.024767571743 0.024768573374 0.024768575562
      2       0.009181708346 0.009181709662 0.009183243460 0.009183244776
15    0       0.096689606435 0.096689590595 0.096690288834 0.096690272994
      1       0.139943460850 0.139943545200 0.139944050635 0.139944134985
      2       0.077843571415 0.077843576029 0.077843805755 0.077843810370
16    0       0.111476433258 0.111476418194 0.111476830858 0.111476815794
      1       0.150260572312 0.150260656600 0.150260972866 0.150261057155
      2       0.094292305869 0.094292310944 0.094292412979 0.094292418054
17    0       0.038730245981 0.038730251148 0.038730916344 0.038730921511
      1       0.024348632985 0.024348637332 0.024349687742 0.024349692089
      2       0.030655094363 0.030655096247 0.030654974584 0.030654976468
18    0       0.081899991991 0.081899992591 0.081900454844 0.081900455444
      1       0.081044702405 0.081044703000 0.081045485002 0.081045485597
      2       0.082344738160 0.082344738764 0.082345316019 0.082345316622

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       0.086293609314 0.086293607628 -0.019215542179 -0.019215541683
      1       0.099215884583 0.099215887127 -0.022114604822 -0.022114605006
      2       0.126705873520 0.126705878460 -0.028428197747 -0.028428198727
1     0       0.086294111368 0.086294109683 -0.019471435266 -0.019471434765
      1       0.099216363339 0.099216365883 -0.022381804730 -0.022381804933
      2       0.136485999747 0.136486004850 -0.031399298074 -0.031399299110
2     0       0.086294562720 0.086294561035 -0.019736808098 -0.019736807593
      1       0.115379578476 0.115379580993 -0.026649364552 -0.026649364793
      2       0.136486242522 0.136486247625 -0.031934401866 -0.031934402952
3     0       0.000002230907 0.000002230906 -0.000000000527 -0.000000000523
      1       0.013465753609 0.013465753772  0.003003659683  0.003003659693
      2       0.011293247352 0.011293247489  0.002504880379  0.002504880403
4     0       0.096702430311 0.096702428365 -0.022232836983 -0.022232836340
      1       0.141109985498 0.141109991082 -0.032430845060 -0.032430846070
      2       0.109761746670 0.109761746606 -0.025074175015 -0.025074174963
5     0       0.000002196491 0.000002196491 -0.000000000035 -0.000000000035
      1       0.031241314174 0.031241314380  0.007021404673  0.007021404674
      2       0.015629281259 0.015629281345  0.003511554757  0.003511554758
6     0       0.041863742817 0.041863750556 -0.006582040270 -0.006582041117
      1       0.094694504639 0.094694524110 -0.020677262061 -0.020677265782
      2       0.092237099742 0.092237111736 -0.018630530771 -0.018630532875
7     0       0.056516630335 0.056516637364 -0.011663491217 -0.011663492168
      1       0.106079748655 0.106079768134 -0.023872077692 -0.023872081590
      2       0.100203120830 0.100203132901 -0.021406433826 -0.021406436070
8     0       0.085521159813 0.085521167012 -0.019282672921 -0.019282674141
      1       0.122342191078 0.122342211295 -0.028137247737 -0.028137251978
      2       0.122450150777 0.122450163733 -0.027737899963 -0.027737902584
9     0       0.127405966551 0.127405975722 -0.029522296607 -0.029522298372
      1       0.151582237452 0.151582260155 -0.035524202659 -0.035524207675
      2       0.136448404189 0.136448418159 -0.031719204381 -0.031719207381
10    0       0.000002222146 0.000002222146 -0.000000002526 -0.000000002526
      1       0.009989440861 0.009989442015  0.002295239719  0.002295239965
      2       0.009988832035 0.009988833189  0.001710748667  0.001710748886
11    0       0.051517169793 0.051517167583 -0.003577209226 -0.003577203293
      1       0.111526161292 0.111526249826 -0.018803749565 -0.018803765034
      2       0.028361400197 0.028361408672 -0.006025056383 -0.006025056122
12    0       0.047536949474 0.047536934803 -0.008023343253 -0.008023337315
      1       0.111527564583 0.111527653116 -0.019160468356 -0.019160484309
      2       0.053970714719 0.053970722409 -0.011688438400 -0.011688438133
13    0       0.047589631009 0.047589636940  0.010781666902  0.010781667977
      1       0.044304506807 0.044304511418  0.008245378803  0.008245378830
      2       0.022465400750 0.022465401967  0.005146663887  0.005146664103
14    0       0.018981635519 0.018981637988  0.004130663759  0.004130664295
      1       0.024768573374 0.024768575562  0.004892578433  0.004892578511
      2       0.009183243460 0.009183244776  0.001508498922  0.001508499230
15    0       0.096690288834 0.096690272994 -0.020651979212 -0.020651974538
      1       0.139944050635 0.139944134985 -0.030478576182 -0.030478592771
      2       0.077843805755 0.077843810370 -0.017933074980 -0.017933075243
16    0       0.111476830858 0.111476815794 -0.024779851166 -0.024779846666
      1       0.150260972866 0.150261057155 -0.033788568408 -0.033788585835
      2       0.094292412979 0.094292418054 -0.022034344778 -0.022034345404
17    0       0.038730916344 0.038730921511  0.008393097194  0.008393098141
      1       0.024349687742 0.024349692089  0.004942436114  0.004942436539
      2       0.030655094363 0.030655096247  0.007255445117  0.007255445488
18    0       0.081900454844 0.081900455444  0.018436364875  0.018436364881
      1       0.081045485002 0.081045485597  0.017385305530  0.017385305536
      2       0.082345316019 0.082345316622  0.018279307665  0.018279307672

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0        0.019471435266  0.019471434765  0.005282959937
      1        0.022381804730  0.022381804933  0.005995188599
      2        0.028899298072  0.028899299097  0.006933000685
1     0        0.019736808098  0.019736807593  0.004827298990
      1        0.022649364539  0.022649364761  0.005378200807
      2        0.031934401866  0.031934402952  0.005018780883
2     0        0.020000000846  0.020000000337  0.004377516769
      1        0.026996340045  0.026996340307  0.003748395629
      2        0.032495118460  0.032495119597  0.003963836486
3     0        0.000000000004 -0.000000000000 -0.000000526837
      1       -0.003000000000 -0.003000000010  0.001010005548
      2       -0.002499999981 -0.002500000005  0.001006016959
4     0        0.022500000613  0.022499999962  0.002106890454
      1        0.032978594262  0.032978595326  0.003196174457
      2        0.025488445247  0.025488445204  0.003718153690
5     0        0.000000000000  0.000000000000 -0.000000512197
      1       -0.007000000073 -0.007000000073  0.002052849875
      2       -0.003500000000 -0.003500000000  0.001012041071
6     0        0.006663491270  0.006663492145  0.007080986320
      1        0.020872077785  0.020872081597  0.007119547409
      2        0.018906433889  0.018906436076  0.010326530939
7     0        0.011782673116  0.011782674098  0.005760658153
      1        0.024137248001  0.024137252004  0.005577613586
      2        0.021737900239  0.021737902574  0.008885960796
8     0        0.019522297022  0.019522298284  0.004038593181
      1        0.028524203301  0.028524207677  0.003909788713
      2        0.028219204673  0.028219207412  0.006345725745
9     0        0.030000000689  0.030000002526  0.001561679263
      1        0.036166722234  0.036166727448  0.001017747718
      2        0.032327280556  0.032327283701  0.004500443454
10    0        0.000000000000 -0.000000000000 -0.000000523322
      1       -0.002292245548 -0.002292245793 -0.000642689878
      2       -0.001707753989 -0.001707754207  0.001653593364
11    0        0.003650383081  0.003650377181  0.011346370046
      1        0.019160468356  0.019160484309  0.017600229324
      2        0.006061398472  0.006061398267  0.002568252677
12    0        0.008074191706  0.008074185738  0.007283126960
      1        0.019517196228  0.019517212665  0.016909609298
      2        0.011798533410  0.011798533239  0.004391144715
13    0       -0.010713723813 -0.010713724870  0.000215614678
      1       -0.008186492723 -0.008186492736  0.005799414702
      2       -0.005131524217 -0.005131524432  0.000829468221
14    0       -0.004119855068 -0.004119855602 -0.001095260265
      1       -0.004874173709 -0.004874173783  0.002664030580
      2       -0.001505970309 -0.001505970616  0.001493259260
15    0        0.020887002694  0.020886997896  0.007317077271
      1        0.031074052557  0.031074069768  0.009219098453
      2        0.018141709857  0.018141710240  0.002169349576
16    0        0.025098007093  0.025098002443  0.005115762974
      1        0.034478621252  0.034478639356  0.006891097669
      2        0.022332377252  0.022332378025  0.001421884563
17    0       -0.008348095751 -0.008348096685  0.002806626665
      1       -0.004924647528 -0.004924647946  0.002759388049
      2       -0.007227255002 -0.007227255370 -0.000385577506
18    0       -0.018224165137 -0.018224165137  0.004223745981
      1       -0.017195706788 -0.017195706787  0.006932423714
      2       -0.018080128090 -0.018080128091  0.005244302596

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss  \
index circuit
0     0         0.005282959761 -0.004827298990 -0.004827298823
      1         0.005995189567 -0.005378200807 -0.005378201732
      2         0.006933000640 -0.006018780879 -0.006018780747
1     0         0.004827298823 -0.004377516769 -0.004377516612
      1         0.005378201732 -0.004748395620 -0.004748396502
      2         0.005018780747 -0.003963836486 -0.003963836254
2     0         0.004377516612 -0.003910824612 -0.003910824464
      1         0.003748396502 -0.002921356028 -0.002921356850
      2         0.003963836254 -0.002917368590 -0.002917368262
3     0        -0.000000526836  0.000000000000 -0.000000000000
      1         0.001010005549 -0.000999999986 -0.000999999987
      2         0.001006016961 -0.001000000012 -0.001000000013
4     0         0.002106890863 -0.001499487462 -0.001499487885
      1         0.003196175090 -0.002052849353 -0.002052849877
      2         0.003718152760 -0.003012041933 -0.003012040989
5     0        -0.000000512197  0.000000000000 -0.000000000000
      1         0.002052849877 -0.001999999958 -0.001999999958
      2         0.001012041071 -0.001000000042 -0.001000000042
6     0         0.007080987883 -0.006960658116 -0.006960659633
      1         0.007119549955 -0.006577613558 -0.006577615875
      2         0.010326532555 -0.009885960757 -0.009885962248
7     0         0.005760659634 -0.005538593124 -0.005538594545
      1         0.005577615863 -0.004909788644 -0.004909790668
      2         0.008885962258 -0.008345725593 -0.008345726915
8     0         0.004038594512 -0.003561679055 -0.003561680294
      1         0.003909790657 -0.003017747586 -0.003017749226
      2         0.006345726958 -0.005500443364 -0.005500444384
9     0         0.001561680347 -0.000537630019 -0.000537630929
      1         0.001017749153  0.000320863009  0.000320861988
      2         0.004500444403 -0.003408073333 -0.003408074042
10    0        -0.000000523322  0.000000000000  0.000000000000
      1        -0.000642689968  0.000648143100  0.000648143192
      2         0.001653593520 -0.001648143037 -0.001648143192
11    0         0.011346371296 -0.011161840896 -0.011161842104
      1         0.017600242459 -0.016909609298 -0.016909621348
      2         0.002568258165 -0.002512430886 -0.002512436355
12    0         0.007283128276 -0.007130293056 -0.007130294398
      1         0.016909621348 -0.016218963443 -0.016218974409
      2         0.004391150183 -0.004200766012 -0.004200771440
13    0         0.000215615070 -0.000080208078 -0.000080208433
      1         0.005799416146 -0.005682127358 -0.005682128777
      2         0.000829468329 -0.000799693270 -0.000799693373
14    0        -0.001095259981  0.001116401732  0.001116401453
      1         0.002664031212 -0.002627697499 -0.002627698124
      2         0.001493259351 -0.001488703240 -0.001488703330
15    0         0.007317078125 -0.006736029988 -0.006736030918
      1         0.009219107757 -0.008116309670 -0.008116317712
      2         0.002169354820 -0.001776405217 -0.001776410407
16    0         0.005115763954 -0.004352689825 -0.004352690887
      1         0.006891105407 -0.005613391858 -0.005613398241
      2         0.001421889677 -0.000851695811 -0.000851700847
17    0         0.002806626506 -0.002717109144 -0.002717108959
      1         0.002759389129 -0.002724322298 -0.002724323364
      2        -0.000385577468  0.000441432353  0.000441432323
18    0         0.004223745995 -0.003820947699 -0.003820947700
      1         0.006932423727 -0.006530880913 -0.006530880913
      2         0.005244302607 -0.004848171387 -0.004848171386

                     pl_mw_mc       pl_mw_dss      ql_mvar_mc     ql_mvar_dss
index circuit
0     0        0.000255893086  0.000255893082  0.000455660947  0.000455660938
      1        0.000267199908  0.000267199927  0.000616987792  0.000616987835
      2        0.000471100324  0.000471100370  0.000914219807  0.000914219893
1     0        0.000265372832  0.000265372828  0.000449782221  0.000449782211
      1        0.000267559809  0.000267559828  0.000629805187  0.000629805230
      2        0.000535103792  0.000535103842  0.001054944397  0.001054944494
2     0        0.000263192748  0.000263192744  0.000466692157  0.000466692148
      1        0.000346975493  0.000346975515  0.000827039601  0.000827039652

## Test 13: 20 bus grid with four controlled sgen, asymmetric load and sgen, voltage far above tolerance limits
This is to test possible interactions between controlled sgens located at different points of the grid. All controllers are expected to converge at valid operation points. 
Expecting controllers to decrease voltage towards tolerance band by high reactive power infeed, which is the same at all phases (gang control). Possible active power deration.

In [29]:
net = grids["twenty_bus_system_voltage_far_above_tolerance_limits_voltvar_control.pkl"]
mc.run_pf(net)
for i in [0,1,2,3]:
    check_ctr_sgen_stable_state(net, sgen_first_lvl_idx=i, verbose=True)

print("--- Pre/Post control comparison ---")
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=True) 
print()
mc.run_pf(net, run_control=True)
multiconductor.test.testing_toolbox.print_sgen_stats(net, "", [0,1,2,3], header=False, before_control=False)
print("\n--- Post control results ---")
c = multiconductor.test.testing_toolbox.compare_to_dss(net)
multiconductor.test.testing_toolbox.print_comparison(c)
print("\nbus results")
print(pd.merge(net.res_bus, net.res_bus_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[["vm_pu_mc", "vm_pu_dss", "va_degree_mc", "va_degree_dss"]])
print("\nline results")
cols = [f"{c}{w}" for c in net.res_line_dss.columns for w in ["_mc", "_dss"]]
print(pd.merge(net.res_line, net.res_line_dss, left_index=True, right_index=True, suffixes=('_mc', '_dss'))[cols])

check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.014357872139811018)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.018)!
check_ctr_sgen_stable_state: sgen reactive power (0.0) does not equal target (-0.018)!
--- Pre/Post control comparison ---
Before control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [1.0008, 1.0315, 1.0409] / [1.0408, 1.0707, 1.0433] / [1.0415, 1.0651, 1.0546] / [1.0169, 1.0257, 1.0162]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000]
p_mw: [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000] / [0.050000, 0.060000, 0.040000]
q_mvar: [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000] / [0.000000, 0.000000, 0.000000]

After control
Sgen bus: 17 / 10 / 3 / 5
vm_pu: [0.9801, 1.0104, 1.0209] / [1.0155, 1.0449, 1.0172] / [1.0174, 1.0402, 1.0302] / [1.0169, 1.0257, 1.0162]
sn_mva_limit: [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000] / [0.060000, 0.060000, 0.060000]
sn_mva: [0.050183, 0.059718, 0.040229] / [0.050300, 0.059562, 0.040374] / [0.050508, 0.059627, 0.040633] / [0.050000, 0.060000, 0.040000]
p_mw: [0.050000, 0.059564, 0.040000] / [0.050000, 0.059309, 0.040000] / [0.050000, 0.059198, 0.040000] / [0.050000, 0.060000, 0.040000]
q_mvar: [-0.004282, -0.004282, -0.004282] / [-0.005483, -0.005483, -0.005483] / [-0.007146, -0.007146, -0.007146] / [0.000000, 0.000000, 0.000000]

--- Post control results ---
Max overall vm_pu difference: 3.540499588335788e-08
Max overall va_degree difference: 5.2206981138169795e-06
Max overall i_from_ka difference: 8.8424190858305e-08
Max overall i_to_ka difference: 8.842417911769651e-08
Max overall p_from_mw difference: 1.7716271949463902e-08
Max overall p_to_mw difference: 1.8765841047763132e-08
Max overall q_from_mvar difference: 1.3808032571505091e-08
Max overall q_to_mvar difference: 1.2130697814305424e-08

bus results
                  vm_pu_mc      vm_pu_dss      va_degree_mc     va_degree_dss
index phase
0     0     0.000000000000 0.000000000000    0.000000000000    0.000000000000
      1     1.000001835758 1.000001835759    0.000062017309    0.000062036693
      2     1.000002801070 1.000002801071 -119.999920652997 -119.999920640058
      3     1.000001442852 1.000001442852  120.000050871790  120.000050878254
1     0     0.000000005017 0.000000005017  100.820594844136  100.820594914328
...                    ...            ...               ...               ...
18    3     1.017474342464 1.017474336074  126.011663534719  126.011664405662
19    0     0.000000005203 0.000000005203  108.009177471816  108.009177435743
      1     0.984473898420 0.984473897943   -1.063787340560   -1.063787353348
      2     0.982770546044 0.982770545518 -120.944440100979 -120.944440116670
      3     0.984331366287 0.984331365809  119.001197655007  119.001197631140

[80 rows x 4 columns]

line results
                i_from_ka_mc  i_from_ka_dss     i_to_ka_mc    i_to_ka_dss  \
index circuit
0     0       0.174637103368 0.174637104840 0.174637854238 0.174637855710
      1       0.220753208497 0.220753221870 0.220753916271 0.220753929644
      2       0.152503969469 0.152503968903 0.152504773693 0.152504773128
1     0       0.174637854238 0.174637855710 0.174638500166 0.174638501639
      1       0.220753916271 0.220753929644 0.220754507805 0.220754521178
      2       0.161286052637 0.161286052271 0.161286665847 0.161286665481
2     0       0.174638500166 0.174638501639 0.174639040334 0.174639041806
      1       0.236363930156 0.236363943819 0.236364326355 0.236364340018
      2       0.161286665847 0.161286665481 0.161287186270 0.161287185904
3     0       0.000002206352 0.000002206349 0.000000000019 0.000000000000
      1       0.013190164389 0.013190164768 0.013190873324 0.013190873704
      2       0.011346528159 0.011346528319 0.011347368286 0.011347368446
4     0       0.181089939177 0.181089938659 0.181090069412 0.181090068894
      1       0.223835738953 0.223835749558 0.223835886374 0.223835896979
      2       0.130551434933 0.130551431063 0.130551690408 0.130551686537
5     0       0.000002208725 0.000002208725 0.000000000000 0.000000000000
      1       0.030880847209 0.030880847352 0.030881461684 0.030881461826
      2       0.015572056916 0.015572057005 0.015572669628 0.015572669717
6     0       0.129344350728 0.129344389576 0.129345571797 0.129345610645
      1       0.177060809057 0.177060863654 0.177061715788 0.177061770385
      2       0.122808841020 0.122808855430 0.122810123151 0.122810137561
7     0       0.145644499547 0.145644537519 0.145645424267 0.145645462240
      1       0.187508879208 0.187508933777 0.187509592174 0.187509646743
      2       0.129565791948 0.129565805885 0.129566867343 0.129566881280
8     0       0.173911774814 0.173911813585 0.173912377572 0.173912416343
      1       0.202825710518 0.202825766354 0.202826224698 0.202826280535
      2       0.149647152463 0.149647166375 0.149647882748 0.149647896660
9     0       0.214480202773 0.214480245835 0.214480498182 0.214480541245
      1       0.230604382054 0.230604442223 0.230604646418 0.230604706587
      2       0.162855784933 0.162855799571 0.162856309096 0.162856323735
10    0       0.000002201230 0.000002201230 0.000000000000 0.000000000000
      1       0.009891774691 0.009891776265 0.009891206734 0.009891208307
      2       0.009889680715 0.009889682289 0.009891206734 0.009891208307
11    0       0.094896702383 0.094896711659 0.094898433126 0.094898442403
      1       0.175303985140 0.175304073565 0.175305352812 0.175305441236
      2       0.054387106170 0.054387110984 0.054388326414 0.054388331229
12    0       0.096400558105 0.096400562730 0.096401819262 0.096401823888
      1       0.175305352812 0.175305441236 0.175306634127 0.175306722551
      2       0.079539390393 0.079539393912 0.079540410028 0.079540413547
13    0       0.047761516796 0.047761521170 0.047761542506 0.047761546880
      1       0.044565641758 0.044565645492 0.044566863989 0.044566867723
      2       0.022587416607 0.022587417737 0.022587748541 0.022587749672
14    0       0.019093684214 0.019093686115 0.019093131590 0.019093133491
      1       0.024904862898 0.024904864723 0.024905873875 0.024905875700
      2       0.009162081791 0.009162082619 0.009163603422 0.009163604249
15    0       0.145735796990 0.145735802102 0.145736580289 0.145736585401
      1       0.204039270068 0.204039356088 0.204039956770 0.204040042791
      2       0.101231797653 0.101231798992 0.101232358953 0.101232360292
16    0       0.159817295813 0.159817301086 0.159817826792 0.159817832064
      1       0.213972449836 0.213972536020 0.213972946782 0.213973032965
      2       0.117299126030 0.117299127686 0.117299517909 0.117299519566
17    0       0.038914179277 0.038914183440 0.038914853648 0.038914857810
      1       0.024509018093 0.024509021632 0.024510089422 0.024510092961
      2       0.030982209996 0.030982212199 0.030982064287 0.030982066489
18    0       0.081899902440 0.081899903040 0.081900365294 0.081900365894
      1       0.081044605441 0.081044606036 0.081045388038 0.081045388634
      2       0.082344680622 0.082344681225 0.082345258480 0.082345259084

                     i_ka_mc       i_ka_dss    p_from_mw_mc   p_from_mw_dss  \
index circuit
0     0       0.174637854238 0.174637855710 -0.037481180807 -0.037481180337
      1       0.220753916271 0.220753929644 -0.047724406091 -0.047724408368
      2       0.152504773693 0.152504773128 -0.032432516289 -0.032432516143
1     0       0.174638500166 0.174638501639 -0.038309712994 -0.038309712545
      1       0.220754507805 0.220754521178 -0.049152266912 -0.049152269386
      2       0.161286665847 0.161286665481 -0.035731806130 -0.035731806011
2     0       0.174639040334 0.174639041806 -0.039156222811 -0.039156222382
      1       0.236364326355 0.236364340018 -0.054583291123 -0.054583293857
      2       0.161287186270 0.161287185904 -0.036599057738 -0.036599057638
3     0       0.000002206352 0.000002206349 -0.000000001110 -0.000000001106
      1       0.013190873324 0.013190873704  0.003003574236  0.003003574310
      2       0.011347368286 0.011347368446  0.002504869692  0.002504869715
4     0       0.181090069412 0.181090068894 -0.041670576246 -0.041670575690
      1       0.223835886374 0.223835896979 -0.051465322908 -0.051465325044
      2       0.130551690408 0.130551686537 -0.029869917314 -0.029869916358
5     0       0.000002208725 0.000002208725  0.000000000041  0.000000000041
      1       0.030881461684 0.030881461826  0.007020941041  0.007020941041
      2       0.015572669628 0.015572669717  0.003511423611  0.003511423611
6     0       0.129345571797 0.129345610645 -0.024335853541 -0.024335858863
      1       0.177061715788 0.177061770385 -0.036758485712 -0.036758495253
      2       0.122810123151 0.122810137561 -0.022600470846 -0.022600472052
7     0       0.145645424267 0.145645462240 -0.029826949457 -0.029826955232
      1       0.187509592174 0.187509646743 -0.040621073244 -0.040621083523
      2       0.129566867343 0.129566881280 -0.025625070106 -0.025625071526
8     0       0.173912377572 0.173912416343 -0.037924974617 -0.037924981248
      1       0.202826224698 0.202826280535 -0.045615968217 -0.045615979563
      2       0.149647882748 0.149647896660 -0.032210528715 -0.032210530586
9     0       0.214480498182 0.214480541245 -0.048764974079 -0.048764982237
      1       0.230604646418 0.230604706587 -0.053828235593 -0.053828248840
      2       0.162856309096 0.162856323735 -0.036460142574 -0.036460144893
10    0       0.000002201230 0.000002201230 -0.000000001662 -0.000000001662
      1       0.009891774691 0.009891776265  0.002314962784  0.002314963131
      2       0.009891206734 0.009891208307  0.001690908062  0.001690908407
11    0       0.094898433126 0.094898442403 -0.012856088438 -0.012856086480
      1       0.175305352812 0.175305441236 -0.030827983857 -0.030827998557
      2       0.054388326414 0.054388331229 -0.010328631933 -0.010328630304
12    0       0.096401819262 0.096401823888 -0.017437972020 -0.017437970090
      1       0.175306634127 0.175306722551 -0.031724471572 -0.031724487101
      2       0.079540410028 0.079540413547 -0.016097692758 -0.016097691222
13    0       0.047761542506 0.047761546880  0.010750972450  0.010750973153
      1       0.044566863989 0.044566867723  0.008261698711  0.008261698824
      2       0.022587748541 0.022587749672  0.005162717114  0.005162717312
14    0       0.019093684214 0.019093686115  0.004122867329  0.004122867681
      1       0.024905873875 0.024905875700  0.004898021148  0.004898021241
      2       0.009163603422 0.009163604249  0.001511174705  0.001511174895
15    0       0.145736580289 0.145736585401 -0.030190490692 -0.030190489611
      1       0.204039956770 0.204040042791 -0.043598639405 -0.043598655969
      2       0.101232358953 0.101232360292 -0.022503526624 -0.022503525529
16    0       0.159817826792 0.159817832064 -0.034579498244 -0.034579497336
      1       0.213972946782 0.213973032965 -0.047584404274 -0.047584421991
      2       0.117299517909 0.117299519566 -0.026788901093 -0.026788900342
17    0       0.038914853648 0.038914857810  0.008336148603  0.008336149234
      1       0.024510089422 0.024510092961  0.004968193419  0.004968193811
      2       0.030982209996 0.030982212199  0.007287905097  0.007287905522
18    0       0.081900365294 0.081900365894  0.018436367105  0.018436367111
      1       0.081045388038 0.081045388634  0.017385308425  0.017385308431
      2       0.082345258480 0.082345259084  0.018279301343  0.018279301350

                   p_to_mw_mc     p_to_mw_dss  q_from_mvar_mc  \
index circuit
0     0        0.038309712994  0.038309712545  0.014890714089
      1        0.049152266912  0.049152269386  0.017928595658
      2        0.033231806126  0.033231805997  0.013730746074
1     0        0.039156222811  0.039156222382  0.012977738527
      1        0.050583291156  0.050583293827  0.015153269570
      2        0.036599057738  0.036599057638  0.011309199094
2     0        0.040000001324  0.040000000916  0.011078496350
      1        0.056194052862  0.056194055810  0.011349513276
      2        0.037495130368  0.037495130289  0.009724167121
3     0        0.000000000004  0.000000000000 -0.000000518390
      1       -0.002999999934 -0.003000000008  0.001009638780
      2       -0.002499999981 -0.002500000004  0.001006170499
4     0        0.042500000431  0.042499999886  0.003543968278
      1        0.052979056658  0.052979058959  0.004844127634
      2        0.030488577328  0.030488576349  0.004097168597
5     0       -0.000000000000  0.000000000000 -0.000000518688
      1       -0.007000000071 -0.007000000071  0.002051682787
      2       -0.003500000000 -0.003500000000  0.001012002276
6     0        0.024826949612  0.024826955209  0.017321492739
      1        0.037621073414  0.037621083531  0.017912325090
      2        0.023125070169  0.023125071530  0.017134613879
7     0        0.030424975135  0.030424981203  0.015035546423
      1        0.041615968692  0.041615979593  0.015115106074
      2        0.026210528991  0.026210530573  0.015262716577
8     0        0.038764975168  0.038764982147  0.012178257092
      1        0.046828236794  0.046828248850  0.012110122698
      2        0.032960142867  0.032960144922  0.012269731499
9     0        0.049999993026  0.050000001643  0.008299767123
      1        0.055448489274  0.055448503412  0.007748683493
      2        0.037354710502  0.037354713036  0.009907413687
10    0       -0.000000000000  0.000000000000 -0.000000516226
      1       -0.002312024792 -0.002312025138 -0.000582316734
      2       -0.001687974516 -0.001687974861  0.001592987265
11    0        0.013073828923  0.013073827015  0.017748518621
      1        0.031724471572  0.031724487101  0.026242280135
      2        0.010461835847  0.010461834299  0.007146855490
12    0        0.017646736234  0.017646734303  0.013245152499
      1        0.032620972383  0.032620988741  0.024557094016
      2        0.016349560204  0.016349558774  0.008842038663
13    0       -0.010682537550 -0.010682538239  0.000197939233
      1       -0.008202112430 -0.008202112533  0.005858422912
      2       -0.005147412851 -0.005147413048  0.000791514968
14    0       -0.004111930607 -0.004111930957 -0.001113703849
      1       -0.004879411095 -0.004879411184  0.002702932612
      2       -0.001508657673 -0.001508657862  0.001473455784
15    0        0.030706748013  0.030706746904  0.012847040570
      1        0.044867046003  0.044867063556  0.015790688761
      2        0.022879010185  0.022879009208  0.006445889433
16    0        0.035208651634  0.035208650687  0.009883518383
      1        0.048986173642  0.048986192407  0.012220028140
      2        0.027277104897  0.027277104284  0.005461254753
17    0       -0.008290718847 -0.008290719467  0.002844295819
      1       -0.004950168093 -0.004950168479  0.002833108139
      2       -0.007259111636 -0.007259112056 -0.000494418652
18    0       -0.018224167804 -0.018224167804  0.004223746445
      1       -0.017195710142 -0.017195710142  0.006932424924
      2       -0.018080122069 -0.018080122069  0.005244298524

               q_from_mvar_dss    q_to_mvar_mc   q_to_mvar_dss  \
index circuit
0     0         0.014890715445 -0.012977738527 -0.012977739811
      1         0.017928597388 -0.015153269570 -0.015153270924
      2         0.013730745465 -0.012309199091 -0.012309198463
1     0         0.012977739811 -0.011078496350 -0.011078497564
      1         0.015153270924 -0.012349513257 -0.012349514234
      2         0.011309198463 -0.009724167121 -0.009724166464
2     0         0.011078497564 -0.009145226354 -0.009145227496
      1         0.011349514234 -0.008155384135 -0.008155384680
      2         0.009724166464 -0.008151917087 -0.008151916403
3     0        -0.000000518389  0.000000000001  0.000000000000
      1         0.001009638795 -0.000999999973 -0.000999999988
      2         0.001006170517 -0.000999999995 -0.001000000012
4     0         0.003543970035 -0.001499479670 -0.001499481393
      1         0.004844127307 -0.002051683432 -0.002051682788
      2         0.004097167476 -0.003012003273 -0.003012002195
5     0        -0.000000518688 -0.000000000000  0.000000000000
      1         0.002051682788 -0.001999999959 -0.001999999959
      2         0.001012002277 -0.001000000041 -0.001000000041
6     0         0.017321500382 -0.016235546317 -0.016235553294
      1         0.017912333658 -0.016115106008 -0.016115113465
      2         0.017134617476 -0.016262716534 -0.016262719892
7     0         0.015035553295 -0.013678256862 -0.013678263005
      1         0.015115113453 -0.013110122564 -0.013110128771
      2         0.015262719903 -0.014269731330 -0.014269734403
8     0         0.012178262970 -0.010299766625 -0.010299771630
      1         0.012110128760 -0.009748683221 -0.009748687984
      2         0.012269734449 -0.010907413584 -0.010907416226
9     0         0.008299771681 -0.005482012817 -0.005482016187
      1         0.007748687912 -0.004724662799 -0.004724665639
      2         0.009907416248 -0.008251067512 -0.008251069708
10    0        -0.000000516226  0.000000000000 -0.000000000000
      1        -0.000582316879  0.000587639134  0.000587639281
      2         0.001592987394 -0.001587639154 -0.001587639281
11    0         0.017748522500 -0.017139561784 -0.017139565443
      1         0.026242293943 -0.024557094016 -0.024557106147
      2         0.007146859647 -0.006947629406 -0.006947633543
12    0         0.013245156181 -0.012634546523 -0.012634550044
      1         0.024557106147 -0.022871873443 -0.022871883896
      2         0.008842042805 -0.008425075659 -0.008425079769
13    0         0.000197939406 -0.000061542049 -0.000061542195
      1         0.005858423911 -0.005739735825 -0.005739736802
      2         0.000791515022 -0.000761406114 -0.000761406163
14    0        -0.001113703736  0.001135108305  0.001135108196
      1         0.002702933068 -0.002666189465 -0.002666189915
      2         0.001473455828 -0.001468918239 -0.001468918282
15    0         0.012847043880 -0.011517236980 -0.011517240055
      1         0.015790698040 -0.013478759123 -0.013478766516
      2         0.006445893450 -0.005768804894 -0.005768808872
16    0         0.009883521456 -0.008301005340 -0.008301008159
      1         0.012220035280 -0.009667030057 -0.009667035213
      2         0.005461258706 -0.004560015648 -0.004560019541
17    0         0.002844295780 -0.002753910482 -0.002753910422
      1         0.002833108957 -0.002797576586 -0.002797577392
      2        -0.000494418685  0.000551487771  0.000551487813
18    0         0.004223746459 -0.003820949061 -0.003820949062
      1         0.006932424937 -0.006530883056 -0.006530883056
      2         0.005244298535 -0.004848167883 -0.004848167882

                     pl_mw_mc       pl_mw_dss      ql_mvar_mc     ql_mvar_dss
index circuit
0     0        0.000828532187  0.000828532207  0.001912975562  0.001912975634
      1        0.001427860821  0.001427861018  0.002775326089  0.002775326463
      2        0.000799289837  0.000799289854  0.001421546983  0.001421547002
1     0        0.000846509817  0.000846509837  0.001899242176  0.001899242247
      1        0.001431024243  0.001431024441  0.002803756313  0.002803756690
      2        0.000867251608  0.000867251628  0.001585031973  0.001585031999
2     0        0.000843778514  0.000843778535  0.001933269996  0.001933270068
      1        0.001610761739  0.001610761953  0.003194129141  0.003194129555